### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by otcbl1nk** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#105]
The latest update to the component looks to have broken things completely for me. I am seeing a division by zero error with the new parse_obstacles code:

2021-04-25 11:54:55 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.roborock_s6_maxv fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 292, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 490, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 225, in update
    map_data, map_stored = self._connector.get_map(self._country, map_name, self._colors, self._drawables,
  File "/config/custom_components/xiaomi_cloud_map_extractor/xiaomi_cloud_connector.py", line 139, in get_map
    map_data = MapDataParser.parse(unzipped, colors, drawables, texts, sizes, image_config)
  File "/config/custom_components/xiaomi_cloud_map_extractor/map_data_parser.py", line 87, in parse
    map_data.obstacles_with_photo = MapDataParser.parse_obstacles(data, header)
  File "/config/custom_components/xiaomi_cloud_map_extractor/map_data_parser.py", line 199, in parse_obstacles
    #    details[ATTR_CONFIDENCE_LEVEL] = u1 * 10.0 / u2
ZeroDivisionError: float division by zero

**Comment by PiotrMachowski** [comment]
Which model do you have? Can you also enable `store_map` option and send me `map_data.gz` file? It should be stored in `/tmp` directory

**Comment by gjohansson-ST** [comment]
Same issue with a new S6 MaxV

**Comment by PiotrMachowski** [comment]
@gjohansson-ST What type of installation do you have?

**Comment by gjohansson-ST** [comment]
> @gjohansson-ST What type of installation do you have?

Supervised running on Ubuntu.
Both core and supervisor on latest version.

**Comment by PiotrMachowski** [comment]
@gjohansson-ST in this case map file should be in HA container in temp directory (not in OS)

**Comment by gjohansson-ST** [comment]
> @gjohansson-ST in this case map file should be in HA container in temp directory (not in OS)

It's not. That's were I was looking for it.

**Comment by PiotrMachowski** [comment]
Fixed in v1.1.1

@gjohansson-ST please check if map file is available after updating to latest version

**Comment by gjohansson-ST** [comment]
Hi. I remade the map before you solved it. Apparently I had something wrong in the map from the first run.
Regardless thanks for fixing it!

**Comment by PiotrMachowski** [comment]
@gjohansson-ST that's great 👍 

PS now you can approve my [PR in HACS](https://github.com/hacs/default/pull/887) 😃

**Comment by gjohansson-ST** [comment]
> PS now you can approve my [PR in HACS](https://github.com/hacs/default/pull/887) 😃

Done ✅
