### ISSUE TITLE
name 'map_to_image' is not defined

### ISSUE THREAD

**Issue by Deejayfool** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#133]
Hello,

Since the upgrade to v2.0.0, I get the following error in Core logs :

`2021-06-15 07:40:14 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.vacuum fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 350, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 558, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 251, in update
    map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 28, in get_map
    map_data = self.decode_map(response, colors, drawables, texts, sizes, image_config)
  File "/config/custom_components/xiaomi_cloud_map_extractor/xiaomi/vacuum.py", line 28, in decode_map
    return MapDataParserXiaomi.parse(unzipped, colors, drawables, texts, sizes, image_config)
  File "/config/custom_components/xiaomi_cloud_map_extractor/xiaomi/map_data_parser.py", line 99, in parse
    map_data.vacuum_room = MapDataParserXiaomi.get_current_vacuum_room(img_start, raw,
  File "/config/custom_components/xiaomi_cloud_map_extractor/xiaomi/map_data_parser.py", line 119, in get_current_vacuum_room
    x = round(map_to_image(vacuum_position.x) - image_left)
NameError: name 'map_to_image' is not defined`

Have someone else the same problem ?
Or do you know how I can solve it ?

**Comment by Deejayfool** [comment]
I didn't see, it's a duplicate with #132 .
