### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'x'

### ISSUE THREAD

**Issue by Enzokot** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#184]
HA version: 2021.11.1

Logger error:

Logger: homeassistant
Source: custom_components/xiaomi_cloud_map_extractor/common/map_data.py:22
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 16:27:25 (3 occurrences)
Last logged: 16:28:33

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 728, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 473, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 596, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1211, in async_set
    same_attr = old_state.attributes == MappingProxyType(attributes)
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/map_data.py", line 22, in __eq__
    return self.x == other.x and self.y == other.y and self.a == other.a
AttributeError: 'NoneType' object has no attribute 'x'

**Comment by PiotrMachowski** [comment]
Problem should be solved in v2.1.2
