### ISSUE TITLE
Can not retrieve xiaomi map

### ISSUE THREAD

**Issue by wajo666** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#213]
This error originated from a custom integration.

Logger: custom_components.xiaomi_cloud_map_extractor.camera
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:288
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 21:04:58 (65 occurrences)
Last logged: 21:15:46

Failed to retrieve model

**Comment by derretro** [comment]
Same here, the Xiaomi token extractor says „Unauthorized“. Seems like something was changed by Xiaomi. Probably only the EU/German servers are affected.

**Comment by tigger1972** [comment]
Same here!

**Comment by tars-domoticz** [comment]
Same error here (Spain). Token extractor says "Unable to get devices". I also think that Xiaomi has changed something.

**Comment by TTLucian** [comment]
Same here:
```
Logger: custom_components.xiaomi_cloud_map_extractor.camera
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:288
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 18:13:00 (4737 occurrences)
Last logged: 23:11:39

Failed to retrieve model
```

**Comment by mateuszdrab** [comment]
Here was me waiting all day to see if it resolves itself, glad to see I'm not the only one.
Xiaomi must have definitely made a change, during the time the component stopped working, I was also unable to get the map in the official app - this now works, but the component remains dead.

`Logger: homeassistant.helpers.entity
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:299
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 31 December 2021, 23:04:23 (4 occurrences)
Last logged: 18:10:59

Update for camera.xiaomi_cloud_map_extractor fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(4096)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(4096)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(4096)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 699, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 252, in update
    map_name = self._handle_map_name(counter)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 299, in _handle_map_name
    map_name = self._vacuum.map()[0]
  File "/usr/local/lib/python3.9/site-packages/miio/click_common.py", line 187, in _wrap
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/miio/integrations/vacuum/roborock/vacuum.py", line 365, in map
    return self.send("get_map_v1")
  File "/usr/local/lib/python3.9/site-packages/miio/device.py", line 103, in send
    return self._protocol.send(
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 233, in send
    return self.send(
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 233, in send
    return self.send(
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 233, in send
    return self.send(
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 194, in send
    m = Message.parse(data, token=self.token)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 288, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 300, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 1981, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 2439, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 4265, in _parse
    obj = self.subcon._parsereport(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 1981, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 2511, in _parse
    raise ConstError("parsing expected %r but parsed %r" % (self.value, obj), path=path)
construct.core.ConstError: Error in path (parsing) -> header
parsing expected 8497 but parsed 47645`

**Comment by tmjo** [comment]
Same for me.

**Comment by dth97410** [comment]
Same fail for me

**Comment by Tamsy** [comment]
The problem has already been reported [here](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor/issues/50).

**Comment by Rhylthus** [comment]
Same ! Thanks.

**Comment by axcs** [comment]
For those who do not want to wait for the official fix, a file is available here that corrects the situation for now #214

**Comment by PiotrMachowski** [comment]
Problem should be solved in v2.1.2

**Comment by tmjo** [comment]
Great! The new version seems to have solved the issue for me. Thanks!!

**Comment by wajo666** [comment]
Worked for me, thanks

**Comment by mateuszdrab** [comment]
Confirmed working here too, thank you for a quick fix @PiotrMachowski 

Szczęśliwego Nowego Roku!
