### ISSUE TITLE
Support for the 'mijia.vacuum.v2' cleaner.

### ISSUE THREAD

**Issue by OlavRab** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#259]
Hi,

I imported the Map Extractor for my mijia.vacuum.v2 vacuum, but once imported, there is an error code:

 Found an unsupported model 'mijia.vacuum.v2' for class 'RoborockVacuum'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/ 

Anybody else has this vacuum and does have it working? Or is it possible to support this device? It uses the Xiaomi MIOT Auto integration to connect locally.

Thanks already

**Comment by PiotrMachowski** [comment]
Can you check if it works when configuring `force_api` to `viomi`, `roidmi` or `dreame`?

**Comment by TimpP-Spb** [comment]
Hi Piotr, for me it also nor working, if i try use xiaomi, i get message: Filed to rervive map from vacuum

in other case, only gray card

**Comment by PiotrMachowski** [comment]
@TimpP-Spb what do you get in logs when you use different APIs?

**Comment by TimpP-Spb** [comment]
for xiaomi: Got exception while fetching the state: {'code': -9999, 'message': 'undefined command'}
and second: Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds

for viomi: 
Update for camera.xiaomi_cloud_map_extractor fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 514, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 278, in update
    self._handle_map_data(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 335, in _handle_map_data
    map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 27, in get_map
    response = self.get_raw_map_data(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 45, in get_raw_map_data
    map_url = self.get_map_url(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum_v2.py", line 18, in get_map_url
    if api_response is None or "result" not in api_response or "url" not in api_response["result"]:
TypeError: argument of type 'NoneType' is not iterable

for rodmi: same like viomi

for dream: same

**Comment by drunkly** [comment]
Same here for "ijai.vacuum.v19"
Did you find any way to fix it?

**Comment by PiotrMachowski** [comment]
@drunkly https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues/200
This is not a fix, this is a new feature to add

**Comment by atacheev** [comment]
Good day to all,
I really look forward to supporting the mijia.vacuum.v2 model, the problem is the same as described here.

**Comment by n1c0la84** [comment]
Hi!

Any news on ijai.vacuum.v19 support?

**Comment by polako89** [comment]
> Hi!
> 
> Any news on ijai.vacuum.v19 support?

Hello!

I just made it work!

Look at HACS for the integration Xiaomi Miot Auto.
After downloading it, go to configurations > Devices & Services and add the integration.
(My Home Assitant is all in portuguese, so it can be a little bit different in english)

About the card, I´m using the "Vacuum Card", also from HACS.

So far, I didn´t have sucess importing the map, but I will keep trying!
![vacuum](https://user-images.githubusercontent.com/65664467/209708600-dca03209-128d-4390-81ae-3d92bee7feb7.png)

**Comment by Schlupsss** [comment]
Hello there,

Don't know if it can help but I tried also all force_api that I could find. No one would give any results. On the Card (Frontend) "Calibration issue" are mentionned, while on the log of HASS, this is what I have :

`Logger: custom_components.xiaomi_cloud_map_extractor.camera
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:278
Integration: xiaomi_cloud_map_extractor ([documentation](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor), [issues](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues))
First occurred: 16:20:32 (99 occurrences)
Last logged: 16:28:41
Unable to retrieve map data`

What surprises me, is that the script is definetly trying a lot to retrieve the data (More than an hundred time per min according to pi Hole)

The entity has been added by Xaomi Miot Auto with Token extraction. Might be the reason ?

If you need some info or to run some tests let me know

**Comment by PiotrMachowski** [comment]
> What surprises me, is that the script is definetly trying a lot to retrieve the data (More than an hundred time per min according to pi Hole)

Are you sure that this isn't Miot Auto?



> The entity has been added by Xaomi Miot Auto with Token extraction. Might be the reason ?

Are you talking about vacuum entity?

**Comment by Schlupsss** [comment]
> Are you sure that this isn't Miot Auto?

Yes I'm Sure, I removed all integration with Mi Account. The only one that was link with Mi Account was the Map Extractor. 

Here below, The difference with and without Map Extractor.

![image](https://user-images.githubusercontent.com/121687830/210183767-04dd6192-da2a-4739-ba51-53c605c13387.png)

(Mi Account was still link for some light bulb. Went from 1150 to a hundred of queries)

> Are you talking about vacuum entity?

Yes, I use token extraction with Miiot to integrate Mijia.vacuum.v2 I was wondering if the integration would have impact on the map extraction.

**Comment by PiotrMachowski** [comment]
I suppose traffic reflects that Map Extractor tries to download the map every 5s.

Using Miiot integration shouldn't cause Map Extractor to breakn completely.

**Comment by Schlupsss** [comment]
> I suppose traffic reflects that Map Extractor tries to download the map every 5s.

It fits the number of queries. I stopped the map extraction until some workaround is found. No need to stress pi-hole, servers and so on.

In the meantime if you need some info or tests let me know.

**Comment by LedSzef** [comment]
Hello
Any news on mijia.vacuum.v2 support?

**Comment by RayBan91** [comment]
Hello, is there any progress in integraton with mop 2 pro?
