### ISSUE TITLE
Map Extractor don't show map

### ISSUE THREAD

**Issue by galamarco** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#279]
I downloaded and configured Map Extractor but unfortunately the result is null, the map is not shown.
![image](https://www.webg.it/images/articoli/2022-05/Screenshot_76.png)

My config are:
```
 camera:
  - platform: xiaomi_cloud_map_extractor
     host: 192.168.6.33
     token: '49454f7663776f65384XXXXXXXXX'
     username: '+39344XXXXXX'
     password: 'XXXXXXXXXXX'
```

In developer tool I have this:

![image](https://www.webg.it/images/articoli/2022-05/Screenshot_77.png)

In error log I have this:
```
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: homeassistant.helpers.entity
Source: custom_components/xiaomi_cloud_map_extractor/viomi/vacuum.py:14
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 12:30:37 (613 occurrences)
Last logged: 13:21:58

Update for camera.xiaomi_cloud_map_extractor fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 514, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 261, in update
    self._handle_map_data(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 318, in _handle_map_data
    map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 28, in get_map
    map_data = self.decode_map(response, colors, drawables, texts, sizes, image_config)
  File "/config/custom_components/xiaomi_cloud_map_extractor/viomi/vacuum.py", line 14, in decode_map
    unzipped = zlib.decompress(raw_map)
zlib.error: Error -3 while decompressing data: incorrect header check
```
System information
I'm using Home Assistant 2022.4.7
Xiaomi Cloud Map Extractor 2.71
Xiaomi Miot Auto 53.08

Best regards
Marco

**Comment by PiotrMachowski** [comment]
Can you send me raw map file?

[Retrieving map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map)

`piotr.machowski.dev [at] gmail.com`

**Comment by galamarco** [comment]
I'm sorry but the map doesn't seem to be generated
Following this step
```
Retrieving map
When store_map_raw: true is added to your config this integration will store a raw map file in /tmp directory. If you don't use Core installation ([installation types](https://www.home-assistant.io/installation/#compare-installation-methods)) you can retrieve this file in the following way:

In [SSH & Terminal add-on](https://github.com/hassio-addons/addon-ssh) enable protected access
Open terminal and use the following command to copy file:
docker exec homeassistant bash -c "mkdir -p /config/tmp/ && cp /tmp/map_* /config/tmp/"
Map file will appear in tmp folder in your config folder
```
I get this result

![image](https://www.webg.it/images/articoli/2022-05/Screenshot_38.png)

In "config" folder there ara not "tmp" folder then there isn't 
![image](https://www.webg.it/images/articoli/2022-05/Screenshot_39.png)

**Comment by PiotrMachowski** [comment]
Use `store_map_path: "/config"`

**Comment by galamarco** [comment]
Is the same
![image](https://www.webg.it/images/articoli/2022-05/Screenshot_40.png)

**Comment by PiotrMachowski** [comment]
When you add `store_map_path: "/config"` you don't need to execute `docker ...` command, file should be already there. Aaaaand you are trying to execute said command using wrong terminal addon

**Comment by galamarco** [comment]
Thanks so much for the directions, I was able to get the file I just sent by email as requested

Best regards
Marco

**Comment by galamarco** [comment]
Hello, have you any news for me?

**Comment by PiotrMachowski** [comment]
Can you try `force_api: roidmi`?

**Comment by Lydon** [comment]
> Is the same ![image](https://camo.githubusercontent.com/0e3479163d71c3953f863b73001c2a17ba7bc214de94f1243a8ea710d929dabf/68747470733a2f2f7777772e776562672e69742f696d616765732f61727469636f6c692f323032322d30352f53637265656e73686f745f34302e706e67)
> 
> config:
> 
> ```
> camera:
>   - platform: xiaomi_cloud_map_extractor
>     host: 192.168.6.33
>     token: '49454f7663776f65384665334449437a'
>     username: '+393440480329'
>     password: 'Sviluppo.1864'
>     force_api : viomi
>     store_map_raw: true
>     store_map_path: "/config"
> ```
> 
> Error log;
> 
> ```
> Questo errore ha avuto origine da un'integrazione personalizzata.
> 
> Logger: homeassistant.helpers.entity
> Source: custom_components/xiaomi_cloud_map_extractor/viomi/vacuum.py:14
> Integration: xiaomi_cloud_map_extractor (documentation, issues)
> First occurred: 08:30:05 (1366 occurrences)
> Last logged: 10:24:44
> 
> Update for camera.xiaomi_cloud_map_extractor fails
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 514, in async_update_ha_state
>     await self.async_device_update()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_device_update
>     raise exc
>   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 261, in update
>     self._handle_map_data(map_name)
>   File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 318, in _handle_map_data
>     map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
>   File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 28, in get_map
>     map_data = self.decode_map(response, colors, drawables, texts, sizes, image_config)
>   File "/config/custom_components/xiaomi_cloud_map_extractor/viomi/vacuum.py", line 14, in decode_map
>     unzipped = zlib.decompress(raw_map)
> zlib.error: Error -3 while decompressing data: incorrect header check
> ```

@galamarco I suggest you remove you're xiaomi credentials as you're exposing them 😢

**Comment by galamarco** [comment]
thanks for reporting, but the credentials given here are not valid now.

**Comment by PiotrMachowski** [comment]
@galamarco 

You can make your vacuum work by adding `force_api: roidmi` to your config:
```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.6.33
    token: '49454f7663776f65384665334449437a'
    username: '+39XXXXXX'
    password: 'XXXXXX'
    force_api: roidmi
```

**Comment by j1104c** [comment]
@galamarco
hi,i got a problem,i add force_api: roidmi to my configuratin.yaml but xiaomi vacuum map card still not working,the map is not shown,how can i do?

**Comment by j1104c** [comment]
@galamarco
hi this is systeam log
Logger: custom_components.xiaomi_cloud_map_extractor.camera
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:356
Integration: xiaomi_cloud_map_extractor ([documentation](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor), [issues](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues))
First occurred: 04:06:15 (176 occurrences)
Last logged: 04:22:44

Unable to retrieve map data

**Comment by testHAtest** [comment]
did you solve it then? i have the same problem with this error 
<img width="363" alt="Cattura" src="https://user-images.githubusercontent.com/88025386/212642617-f559e4d5-6a58-4773-81f2-f2615576b5c3.PNG">

**Comment by PiotrMachowski** [comment]
@testHAtest which model do you have?

**Comment by testHAtest** [comment]
xiaomi robot vacuum-mop 2s 
<img width="453" alt="Cattura" src="https://user-images.githubusercontent.com/88025386/212660918-7be49028-a14b-4499-89a7-4021c64659a2.PNG">

**Comment by PiotrMachowski** [comment]
https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues/200

**Comment by testHAtest** [comment]
thanks :-)

**Comment by xvluny** [comment]
I seem to have the same issue with a Dreame l10s pro. Any  hints? Unfortunately I do not seem to be allowed to attach the map file here...

`Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.helpers.entity
Source: custom_components/xiaomi_cloud_map_extractor/dreame/map_data_parser.py:51
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 23:07:36 (6 occurrences)
Last logged: 23:08:26

Update for camera.xiaomi_cloud_map_extractor fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 722, in async_device_update
    raise exc
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_cloud_map_extractor/camera.py", line 278, in update
    self._handle_map_data(map_name)
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_cloud_map_extractor/camera.py", line 335, in _handle_map_data
    map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 36, in get_map
    map_data = self.decode_map(response, colors, drawables, texts, sizes, image_config)
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_cloud_map_extractor/dreame/vacuum.py", line 24, in decode_map
    return MapDataParserDreame.decode_map(raw_map_string, colors, drawables, texts, sizes, image_config)
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_cloud_map_extractor/dreame/map_data_parser.py", line 51, in decode_map
    unzipped = zlib.decompress(base64.decodebytes(raw_map_string.encode("utf8")))
zlib.error: Error -3 while decompressing data: incorrect header check
`
