### ISSUE TITLE
map not showing - camera_image() got an unexpected keyword argument 'width'

### ISSUE THREAD

**Issue by david1155** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#284]
Home Assistant Core 2022.5.3
Frontend version: 20220504.1 - latest

running in docker container image: _ghcr.io/home-assistant/home-assistant:stable_

Config:
```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 'REDACTED'
    token: 'REDACTED'
    username: 'REDACTED'
    password: 'REDACTED'
    store_map_raw: true
    store_map_path: "/config"
    draw: ['all']
    attributes:
      - calibration_points
```

```
# ls -lha config/|grep map
-rw-r--r-- 1 root root  13K May  9 17:57 map_data_roborock.vacuum.a10.gz
```

Logs:
```
.........
2022-05-09 17:51:57 DEBUG (SyncWorker_1) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map from Xiaomi cloud
2022-05-09 17:51:58 DEBUG (SyncWorker_1) [custom_components.xiaomi_cloud_map_extractor.camera] Map data retrieved
2022-05-09 17:51:58 DEBUG (SyncWorker_1) [custom_components.xiaomi_cloud_map_extractor.camera] Map is ok
2022-05-09 17:51:58 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 736, in get
return await self.handle(request, camera)
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 754, in handle
image = await _async_get_image(
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 174, in _async_get_image
if image_bytes := await camera.async_camera_image(
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 581, in async_camera_image
return await self.hass.async_add_executor_job(
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
TypeError: camera_image() got an unexpected keyword argument 'width'
```
![Screenshot 2022-05-09 at 17 55 26](https://user-images.githubusercontent.com/64733669/167437515-cb47b640-f799-4a57-9bf0-c90d327003b9.png)

I am not sure but it may be related to [ Remove legacy compatibility for camera platforms that do not support width/height arguments #68039 ](https://github.com/home-assistant/core/pull/68039) and code should be updated.

**Comment by PiotrMachowski** [comment]
Are you sure that you have the latest version of map extractor? It already has been updated: 
https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/blob/master/custom_components/xiaomi_cloud_map_extractor/camera.py#L184

**Comment by david1155** [comment]
Thank you. I downloaded latest 2.1.3 instead of master branch.

**Comment by PiotrMachowski** [comment]
Ok, I have made GitHub refresh its data
