### ISSUE TITLE
Error getting map for Vacuum-Mop 2S

### ISSUE THREAD

**Issue by LordHenry76** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#310]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

I have problem to get the map.

![immagine_2022-06-20_102832130](https://user-images.githubusercontent.com/65126956/174559176-e1291d6f-652e-453f-a9fd-3ddda5ae39ef.png)

Thanks in advance.

### What version of am integration has described problem?

2.2.0

### What vacuum model do you have problems with?

Vacuum-Mop 2S

### What version of Home Assistant do you use?

2022.6.6

### What type of installation are you running?

Home Assistant Supervised

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.1.24
    token: XXXXXXXXXXXXXXXXXXXXXXXXXXX
    username: XXXXXXXXXXXXXXXXXXXXXXX
    password: XXXXXXXXXXXX
    draw: ["all"]
    attributes:
      - calibration_points
```

### Errors shown in the HA logs (if applicable)

```shell
Logger: homeassistant.helpers.entity
Source: custom_components/xiaomi_cloud_map_extractor/common/vacuum_v2.py:18
Integration: xiaomi_cloud_map_extractor ([documentation](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor), [issues](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues))
First occurred: 10:21:16 (15 occurrences)
Last logged: 10:22:27

Update for camera.xiaomi_cloud_map_extractor fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 278, in update
    self._handle_map_data(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 335, in _handle_map_data
    map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 27, in get_map
    response = self.get_raw_map_data(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 45, in get_raw_map_data
    map_url = self.get_map_url(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum_v2.py", line 18, in get_map_url
    if api_response is None or "result" not in api_response or "url" not in api_response["result"]:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by PiotrMachowski** [comment]
Please provide model name in following format: `roborock.vacuum.a27`

**Comment by LordHenry76** [comment]
> Please provide model name in following format: `roborock.vacuum.a27`

Where I can find this info?

**Comment by danichispa** [comment]
Xiaomi Mop 2S is `ijai.vacuum.v19`

**Comment by LordHenry76** [comment]
Thank's danichispa.

So now what I can do?

**Comment by PiotrMachowski** [comment]
Ijai vacuums are not supported at this moment, you can follow this issue for any updates on this case: #200
