### ISSUE TITLE
Doesn't work for dreame.vacuum.r2228

### ISSUE THREAD

**Issue by aureole999** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#335]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

It doesn't work for my dreame.vacuum.r2228.
Seems segment_id is larger than the size of ROOM_COLORS, so I temporarily changed a little bit to get round it.
```
default = ImageHandler.ROOM_COLORS[(segment_id >> 1) & 0b01111]
```
Then it can show the map without any problem.

### What version of am integration has described problem?

v2.2.0

### What vacuum model do you have problems with?

dreame.vacuum.r2228

### What version of Home Assistant do you use?

2022.8.7

### What type of installation are you running?

Home Assistant Container

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    name: dreame_map
    host: "192.168.1.33"
    token: "xxxx"
    username: "xxxx"
    password: "xxxx"
    draw: ['all']
    attributes:
      - calibration_points
      - rooms
```

### Errors shown in the HA logs (if applicable)

```shell
Update for camera.dreame_map fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 514, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 709, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 278, in update
    self._handle_map_data(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 335, in _handle_map_data
    map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 36, in get_map
    map_data = self.decode_map(response, colors, drawables, texts, sizes, image_config)
  File "/config/custom_components/xiaomi_cloud_map_extractor/dreame/vacuum.py", line 24, in decode_map
    return MapDataParserDreame.decode_map(raw_map_string, colors, drawables, texts, sizes, image_config)
  File "/config/custom_components/xiaomi_cloud_map_extractor/dreame/map_data_parser.py", line 52, in decode_map
    return MapDataParserDreame.parse(unzipped, colors, drawables, texts, sizes, image_config, map_data_type)
  File "/config/custom_components/xiaomi_cloud_map_extractor/dreame/map_data_parser.py", line 80, in parse
    rism_map_data = MapDataParserDreame.decode_map(
  File "/config/custom_components/xiaomi_cloud_map_extractor/dreame/map_data_parser.py", line 52, in decode_map
    return MapDataParserDreame.parse(unzipped, colors, drawables, texts, sizes, image_config, map_data_type)
  File "/config/custom_components/xiaomi_cloud_map_extractor/dreame/map_data_parser.py", line 75, in parse
    map_data.image, map_data.rooms = MapDataParserDreame.parse_image(image_raw, header, colors, image_config,
  File "/config/custom_components/xiaomi_cloud_map_extractor/dreame/map_data_parser.py", line 154, in parse_image
    image, image_rooms = ImageHandlerDreame.parse(image_raw, header, colors, image_config, map_data_type)
  File "/config/custom_components/xiaomi_cloud_map_extractor/dreame/image_handler.py", line 81, in parse
    default = ImageHandler.ROOM_COLORS[segment_id >> 1]
IndexError: list index out of range
```

**Comment by PiotrMachowski** [comment]
Can you share a list of your room numbers?

**Comment by aureole999** [comment]
Here it is
```
calibration_points: 
- vacuum:
    x: 0
    'y': 0
  map:
    x: 102
    'y': 141
- vacuum:
    x: 1000
    'y': 0
  map:
    x: 122
    'y': 141
- vacuum:
    x: 0
    'y': 1000
  map:
    x: 102
    'y': 121

room_numbers: 
'1': '1'
'3': '3'
'4': '4'
'5': '5'
'6': '6'
'65': '65'

rooms: 
'1':
  x0: -4750
  y0: 650
  x1: -2500
  y1: 3150
  name: '1'
'3':
  x0: -3200
  y0: 3650
  x1: 250
  y1: 6850
  name: '3'
'4':
  x0: -4850
  y0: -1200
  x1: -2450
  y1: 400
  name: '4'
'5':
  x0: -2450
  y0: 950
  x1: 1150
  y1: 3650
  name: '5'
'6':
  x0: -2400
  y0: -1500
  x1: 600
  y1: 900
  name: '6'
'65':
  x0: -4250
  y0: 1850
  x1: -3400
  y1: 3050
  name: '65'

vacuum_position: 
x: -500
'y': -18
a: 359
```

**Comment by aureole999** [comment]
> Ok, room `65` seems to be a troublemaker 😃 hace you tred room cleaning using this ID from HA?

No, I'm still trying to figure out how to clean a room by room id from HA.
I have only 5 rooms which I believe they are 1,3,4,5,6. and a keep out area. I deleted the keep out area the room 65 is still there.
Then I merged all my rooms, the room list became to:
```
room_numbers: 
'4': '4'
'68': '68'
```

**Comment by PiotrMachowski** [comment]
What integration do you use?

**Comment by aureole999** [comment]
Miot Auto
https://github.com/al-one/hass-xiaomi-miot

**Comment by PiotrMachowski** [comment]
https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/406

https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/317

**Comment by aureole999** [comment]
Ok, I split it to 4 rooms again, and the extra room number became to 71.
Then I started clean by this
```
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.dreame_r2228_d27c_robot_cleaner
  siid: 4
  aiid: 1
  params:
    - piid: 1
      value: 18
    - piid: 10
      value: "{\"selects\":[[71,1,2,2,1]]}"
  throw: true
```
And the robot said it can't go the specfied room.
Maybe I should delete the map and recreate it again?

**Comment by PiotrMachowski** [comment]
> Maybe I should delete the map and recreate it again?

If it's not a big problem I would try this approach

**Comment by aureole999** [comment]
I recreated the map, it automaticlly splited the map to 4 rooms, but there is still a room with id 65.
```
room_numbers: 
'1': '1'
'2': '2'
'3': '3'
'4': '4'
'65': '65'
```
I just let the robot build the map quickly and then did nothing in the app.

**Comment by qjz601** [comment]
Where files need to be modified
`default = ImageHandler.ROOM_COLORS[(segment_id >> 1) & 0b01111]`

**Comment by PiotrMachowski** [comment]
I'm working on a new release, this fix will be a part of it

**Comment by qjz601** [comment]
it work！modify file
/config/custom_components/xiaomi_cloud_map_extractor/dreame/map_data_parser.py

**Comment by PiotrMachowski** [comment]
Yes, I know 🙂

**Comment by StayPirate** [comment]
Yes, that actually fixed my issue, but in version 2.2.0 the offending line code is at `config/custom_components/xiaomi_cloud_map_extractor/dreame/image_handler.py:81`.
