### ISSUE TITLE
Update for camera fails

### ISSUE THREAD

**Issue by marcokitzmann** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#43]
I have also issues with updating the map. Log file says:

```
Logger: homeassistant.helpers.entity
Source: custom_components/xiaomi_cloud_map_extractor/xiaomi_cloud_connector.py:110
First occurred: 8:23:19 (3 occurrences)
Last logged: 8:23:29

Update for camera.herbies_karte fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 190, in update
    map_data = self._connector.get_map(self._country, map_name, self._colors, self._drawables, self._texts,
  File "/config/custom_components/xiaomi_cloud_map_extractor/xiaomi_cloud_connector.py", line 113, in get_map
    response = self.get_raw_map_data(country, map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/xiaomi_cloud_connector.py", line 124, in get_raw_map_data
    map_url = self.get_map_url(country, map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/xiaomi_cloud_connector.py", line 110, in get_map_url
    return api_response["result"]["url"]
TypeError: 'NoneType' object is not subscriptable
```

No idea what to do or if this is a real problem.

**Comment by PiotrMachowski** [comment]
Does the camera work beside this error?

**Comment by marcokitzmann** [comment]
Yes, I have a map and it looks like expected.

**Comment by paperro** [comment]
Im having this problem too
```
2020-11-16 18:24:30 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.vacuumcamera fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 471, in async_device_update
    await self.hass.async_add_executor_job(self.update)  # type: ignore
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 190, in update
    map_data = self._connector.get_map(self._country, map_name, self._colors, self._drawables, self._texts,
  File "/config/custom_components/xiaomi_cloud_map_extractor/xiaomi_cloud_connector.py", line 113, in get_map
    response = self.get_raw_map_data(country, map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/xiaomi_cloud_connector.py", line 124, in get_raw_map_data
    map_url = self.get_map_url(country, map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/xiaomi_cloud_connector.py", line 110, in get_map_url
    return api_response["result"]["url"]
TypeError: 'NoneType' object is not subscriptable
```
