### ISSUE TITLE
Please add support for dreame.vacuum.md1808

### ISSUE THREAD

**Issue by wrewolf** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#450]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the vacuum/platform is already requested
- [ ] I have sent raw map file to `piotr.machowski.dev [at] gmail.com` ([Retrieving map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map); please provide your GitHub username in the email)

### What vacuum model do you want to be supported?

dreame.vacuum.md1808

### What is its name?

Xiaomi Robot Vacuum-Mop 2C

### Available APIs

- [ ] xiaomi
- [ ] viomi
- [ ] roidmi
- [ ] dreame

### Errors shown in the HA logs (if applicable)

```shell
zlib.error: Error -3 while decompressing data: incorrect header check
2023-07-04 12:12:56.062 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.xiaomi_cloud_map_extractor_mop_2c fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 559, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 786, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_cloud_map_extractor/camera.py", line 278, in update
    self._handle_map_data(map_name)
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_cloud_map_extractor/camera.py", line 335, in _handle_map_data
    map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 36, in get_map
    map_data = self.decode_map(response, colors, drawables, texts, sizes, image_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_cloud_map_extractor/viomi/vacuum.py", line 22, in decode_map
    unzipped = zlib.decompress(raw_map)
               ^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by wrewolf** [comment]
[map_data_dreame.vacuum.md1808.b64.txt](https://github.com/user-attachments/files/18077207/map_data_dreame.vacuum.md1808.b64.txt)
