### ISSUE TITLE
Add support for Dreame vacuums with encrypted map

### ISSUE THREAD

**Issue by PiotrMachowski** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#459]
Vacuum models:
* `dreame.vacuum.p2114o`
* `dreame.vacuum.p2149o`
* `dreame.vacuum.p2140o`
* `dreame.vacuum.p2140p`
* `dreame.vacuum.p2114a`
* `dreame.vacuum.r2209`
* `dreame.vacuum.r2254`
* `dreame.vacuum.r2216o`
* `dreame.vacuum.r2235`
* `dreame.vacuum.r2211o`

**Comment by lfdominguez** [comment]
@PiotrMachowski if you need some help, I'm a developer.

**Comment by PiotrMachowski** [comment]
@lfdominguez I'll publish a beta version soon

**Comment by PiotrMachowski** [comment]
There is a _completely untested_ version of Map Extractor that includes these changes [here](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/tree/dev_extracted_libraries), but it needs to be installed manually

**Comment by lfdominguez** [comment]
Thanks, Now I have both installed...

**Comment by PiotrMachowski** [comment]
@lfdominguez please let me know it it works

**Comment by xvluny** [comment]
I ran into an issue installing the dev version because of a python 3.11 requirement. Is this necessary?

**Comment by PiotrMachowski** [comment]
@xvluny the dev version needs HA 2023.8+ which requires python 3.11

**Comment by jhchenchong** [comment]
I tried this branch, but it seems I still get an error.   dreame.vacuum.p2114o   
![Snipaste_2023-09-09_00-44-26](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/19201316/27eea400-3b82-4477-8997-6e2987d7cb2f)

**Comment by PiotrMachowski** [comment]
@jhchenchong thanks for your feedback, I'll check it out

**Comment by PiotrMachowski** [comment]
@Tasshack at this point I think I usually try to redirect to your integration. I do not have as much free time to maintain all of my GitHub projects anymore. Recently though I have got back to rewriting Map Extractor, so there is some hope

**Comment by PiotrMachowski** [comment]
Can you check the new alpha release?

https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/releases/tag/v3.0.0-alpha-1

**Comment by Leblayd** [comment]
@PiotrMachowski I tried the new alpha (version 3) with my dreame.vacuum.p2140p. I added the integration through the UI successfully (but had to use email instead of Username).

However, it doesn't work.
```Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 281, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/coordinator.py", line 35, in update_data
    return await self.connector.get_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/connector/__init__.py", line 65, in get_data
    await self._get_map()
  File "/config/custom_components/xiaomi_cloud_map_extractor/connector/__init__.py", line 117, in _get_map
    await self._update()
  File "/config/custom_components/xiaomi_cloud_map_extractor/connector/__init__.py", line 84, in _update
    map_data, map_saved, map_raw_data = await self._vacuum_connector.get_map()
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/connector/vacuums/base/vacuum_base.py", line 78, in get_map
    map_name = await self.get_map_name()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/connector/vacuums/vacuum_dreame.py", line 63, in get_map_name
    _key = response["result"]["out"][1]["value"]
           ~~~~~~~~~~~~~~~~~~^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

So I went back to alpha-1 just to be sure, and it also fails at the same step, but with a different error (I assume it fails earlier):

```Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 281, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/coordinator.py", line 35, in update_data
    return await self.connector.get_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/connector/__init__.py", line 65, in get_data
    await self._get_map()
  File "/config/custom_components/xiaomi_cloud_map_extractor/connector/__init__.py", line 117, in _get_map
    await self._update()
  File "/config/custom_components/xiaomi_cloud_map_extractor/connector/__init__.py", line 80, in _update
    await self._initialize()
  File "/config/custom_components/xiaomi_cloud_map_extractor/connector/__init__.py", line 99, in _initialize
    device_details = await self._cloud_connector.get_device_details(self._config.token, self._config.server)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/connector/xiaomi_cloud/connector.py", line 287, in get_device_details
    devices = await self.get_devices(server)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/connector/xiaomi_cloud/connector.py", line 277, in get_devices
    device_lists = await asyncio.gather(*device_coro_list)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/connector/xiaomi_cloud/connector.py", line 283, in _get_devices_from_server
    device_lists = await asyncio.gather(*device_coro_list)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/connector/xiaomi_cloud/connector.py", line 264, in _get_devices_from_home
    spec_type=device["spec_type"],
              ~~~~~~^^^^^^^^^^^^^
KeyError: 'spec_type'```
