### ISSUE TITLE
No RepositoryFile.MAINIFEST_JSON file found 'custom_components/xiaomi_cloud_map_extractor/RepositoryFile.MAINIFEST_JSON'

### ISSUE THREAD

**Issue by philharmonie** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#469]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

I try to install the repo using hacs. The UI gives me just "Unknown Error" and the logs give me:
```
2023-09-30 14:05:52.836 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2525935464] Error handling message: Unknown error (unknown_error) admin from 192.168.188.111 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 40, in hacs_repository_info
    await repository.update_repository(ignore_issues=True, force=True)
  File "/config/custom_components/hacs/utils/decorator.py", line 28, in wrapper
    result = await function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/integration.py", line 110, in update_repository
    if manifest := await self.async_get_integration_manifest():
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/integration.py", line 157, in async_get_integration_manifest
    raise HacsException(f"No {RepositoryFile.MAINIFEST_JSON} file found '{manifest_path}'")
custom_components.hacs.exceptions.HacsException: No RepositoryFile.MAINIFEST_JSON file found 'custom_components/xiaomi_cloud_map_extractor/RepositoryFile.MAINIFEST_JSON'
```

### What version of an integration has described problem?

latest

### What vacuum model do you have problems with?

vacuum.roborock_q8_max

### What version of Home Assistant do you use?

Home Assistant 2023.8.4

### What type of installation are you running?

Home Assistant Container

### Camera's configuration

```yaml
none yet
```

**Comment by philharmonie** [comment]
Thank you @PiotrMachowski. After setting everything up fresh, it works. If you don't mind asking here: I used the Roborock app before. Now to generate the token with the token extractor, I needed to pair the vacuum with the Xiaomi Home app. Before that, the official roborock integration generates the vacuum entity. Now it's not working anymore. Even when I try to use the Xiaomi Integration it's not initialising the vacuum.

**Comment by PiotrMachowski** [comment]
You can't use both Roborock integration when you use Xiaomi Home. I suggest going back to Roborock application and using [this integration](https://github.com/humbertogontijo/homeassistant-roborock) - you won't have to use Map Extractor
