### ISSUE TITLE
Request support for ROIDMI EVE CC

### ISSUE THREAD

**Issue by rorog2** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#477]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the vacuum/platform is already requested
- [ ] I have sent raw map file to `piotr.machowski.dev [at] gmail.com` ([Retrieving map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map); please provide your GitHub username in the email)

### What vacuum model do you want to be supported?

roidmi.vacuum.v62

### What is its name?

Roidmi EVE CC

### Available APIs

- [ ] xiaomi
- [ ] viomi
- [X] roidmi
- [ ] dreame

**Comment by PiotrMachowski** [comment]
What doesn't work?

**Comment by rorog2** [comment]
Hello,

The map does not go up in home assistant, here are the logs:

Update for camera.roidmi_eve_cc fails

Traceback (most recent call last):
   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 732, in async_update_ha_state
     await self.async_device_update()
   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 993, in async_device_update
     await hass.async_add_executor_job(self.update)
   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
     result = self.fn(*self.args, **self.kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 278, in update
     self._handle_map_data(map_name)
   File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 335, in _handle_map_data
     map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^
   File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 27, in get_map
     response = self.get_raw_map_data(map_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 45, in get_raw_map_data
     map_url = self.get_map_url(map_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^
   File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum_v2.py", line 18, in get_map_url
     if api_response is None or "result" not in api_response or "url" not in api_response["result"]:
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by ulfdogg** [comment]
any news on this?

**Comment by drcto23** [comment]
Hey all! I can't put the map on the home assistant either, but I did everything according to the description.

Any ideas?

**Comment by LykPapa** [comment]
Hello!

Facing the same issue as @rorog2 

I see that ROIDMI EVE CC (roidmi.vacuum.v62) is not in the "Supported devices" list.
But since roidmi.vacuum.v60 (Roidmi EVE Plus) is, I thought that it could work.
Not the case? 

Anyone had success with ROIDMI EVE CC?

Thank you!

**Comment by Janoku57** [comment]
any news?

**Comment by dibecaspt** [comment]
I have the same problem, there are any news?
