### ISSUE TITLE
Support for xiaomi.vacuum.c103 (Xiaomi Mijia 3C Plus) enhancement new platform

### ISSUE THREAD

**Issue by kennedysmartins** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#491]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the vacuum/platform is already requested
- [ ] I have sent raw map file to `piotr.machowski.dev [at] gmail.com` ([Retrieving map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map); please provide your GitHub username in the email)

### What vacuum model do you want to be supported?

xiaomi.vacuum.c103

### What is its name?

Xiaomi Mijia 3C Plus

### Available APIs

- [ ] xiaomi
- [ ] viomi
- [ ] roidmi
- [ ] dreame

### Errors shown in the HA logs (if applicable)

```shell
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:696
First occurred: 22:04:56 (7 occurrences)
Last logged: 22:05:25

Update for camera.xiaomi_cloud_map_extractor fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 696, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 959, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 278, in update
    self._handle_map_data(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 335, in _handle_map_data
    map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 27, in get_map
    response = self.get_raw_map_data(map_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 45, in get_raw_map_data
    map_url = self.get_map_url(map_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum_v2.py", line 18, in get_map_url
    if api_response is None or "result" not in api_response or "url" not in api_response["result"]:
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

### Other info

I have checked force_api: xiaomi, viomi, roidmi and dreame - no luck...

**Comment by andytion** [comment]
My Mijia Robot Vacuum-Mop 3(xiaomi.vacuum.c104) had same errors shown, i think is the sam framework!

**Comment by maxcoff** [comment]
same wish (xiaomi.vacuum.c103 not work with Xiaomi-Cloud-Map-Extractor)

**Comment by gsaldana** [comment]
Same issue - I've tested all the force_api configuration with no result.

**Comment by kuntet2007** [comment]
B106CN had same issue

**Comment by xvolte** [comment]
https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues/460

if you go there, you will have the new API url, some tools to try to download and decrypt your maps... it is still work in progress, but a good way to start :)
