### ISSUE TITLE
Xiaomi Rovot vaccum and mop 2

### ISSUE THREAD

**Issue by wanderer1983** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#522]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the vacuum/platform is already requested
- [ ] I have sent raw map file to `piotr.machowski.dev [at] gmail.com` ([Retrieving map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map); please provide your GitHub username in the email)

### What vacuum model do you want to be supported?

xiaomi.vacuum.c101

### What is its name?

Mijia Self-Cleaning Robot Vacuum-Mop 2

### Available APIs

- [ ] xiaomi
- [ ] viomi
- [ ] roidmi
- [ ] dreame

### Errors shown in the HA logs (if applicable)

```shell
When forcing an API this is the error:
Logger: miio.miioprotocol
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:320
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 20 March 2024 at 23:22:32 (110 occurrences)
Last logged: 00:04:56

Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}

If not forcing any api:
Update for camera.xiaomi_cloud_map_extractor fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 696, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 959, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 278, in update
    self._handle_map_data(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 335, in _handle_map_data
    map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 27, in get_map
    response = self.get_raw_map_data(map_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 45, in get_raw_map_data
    map_url = self.get_map_url(map_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum_v2.py", line 18, in get_map_url
    if api_response is None or "result" not in api_response or "url" not in api_response["result"]:
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

### Other info

I don't think this vacuum is supported currently.

it simply fails to retrieve the map.

Given that the error is "argument of type 'NoneType' is not iterable" i guess the issue might be that the vacuum is a Mijia (mainland china version) instead of the international Xiaomi, and it cant work out how to handle it.
This vacuum uses the normal Xiaomi app, but needs to be set to mainland china region to work.

**Comment by wanderer1983** [comment]
Also, i did try to force all APIs, All of them time out

**Comment by TheSnowfield** [comment]
Same issue. I dumped the failed API call, and it returns
```
{'code': -6, 'message': 'invalid config for fds', 'result': None}
```

**Comment by TheSnowfield** [comment]
After 2 years. finally I got this :)

<img width="1042" height="923" alt="Image" src="https://github.com/user-attachments/assets/f65a0ce1-b3fd-461e-a1e3-1d7a223b6983" />

**Comment by TheSnowfield** [comment]
The fast test script for model c101. tested. Device region CN

```python
"""render map every 2 sec"""
import os, time, hashlib, base64, zlib, json, math, struct
from Crypto.Cipher import AES
from PIL import Image, ImageDraw, ImageFont
from micloud import MiCloud

# miot config
# these fields can be extracted from /homeassistant/.storage/xiaomi_miot/auth-xxx.json
SERVICE_TOKEN = "" 
SSECURITY = ""
UID = "Your UID"; DID = "Device ID"
MAC = "Device MAC"; MODEL = "c101"; SN = "Device SN"
SCALE = 4; OUT = "map_decoded.png"
REGION = "cn"

# precompute keys
mac_clean = MAC.lower().replace(":", "")
temp_key = (mac_clean + MODEL).encode()
plaintext = f"{SN}+{UID}+{DID}"
def pad(d): p = 16 - len(d) % 16; return d + chr(p) * p
aes_key = AES.new(temp_key, AES.MODE_ECB).encrypt(pad(plaintext).encode())
DECRYPT_KEY = bytes.fromhex(hashlib.md5(base64.b64encode(aes_key)).hexdigest())

# micloud client
mc = MiCloud()
mc.service_token = SERVICE_TOKEN
mc.ssecurity = SSECURITY
mc.user_id = UID
mc.default_server = REGION

def varint(buf, off):
    v=0;s=0
    while True:
        b=buf[off]; v|=(b&0x7F)<<s;s+=7;off+=1
        if not(b&0x80):break
    return v,off

def dfield(buf, off):
    k,off=varint(buf,off)
    fn=k>>3;wt=k&7
    if wt==2: l,off=varint(buf,off); val=buf[off:off+l]; off+=l
    elif wt==0: val,off=varint(buf,off)
    elif wt==5: val=struct.unpack("<f",buf[off:off+4])[0]; off+=4
    else: val=None; off+=1
    return fn,wt,val,off

def decode_fields(buf):
    f={};o=0
    while o<len(buf):
        fn,wt,val,o=dfield(buf,o)
        if fn in f:
            if not isinstance(f[fn],list): f[fn]=[f[fn]]
            f[fn].append(val)
        else: f[fn]=val
    return f

def get_points_list(buf):
    p=[];o=0
    while o<len(buf):
        fn,wt,val,o=dfield(buf,o)
        if fn==4 and wt==2:
            pf=decode_fields(val); p.append((pf.get(1,0.0),pf.get(2,0.0)))
    return p

def api(path, data):
    r=mc.request_country(path,"cn",{"data":json.dumps(data)})
    if isinstance(r,bytes): r=json.loads(r.decode())
    if isinstance(r,dict):
        res=r.get("result",{})
        if isinstance(res,dict) and res.get("url"): return res["url"]
    return None

def download(url):
    import urllib.request
    return urllib.request.urlopen(url,timeout=30).read()

def decrypt(raw):
    b64=base64.b64encode(raw)
    dec=AES.new(DECRYPT_KEY,AES.MODE_ECB).decrypt(base64.b64decode(b64))
    pad_len=dec[-1]
    if 1<=pad_len<=16: dec=dec[:-pad_len]
    return zlib.decompress(bytes.fromhex(dec.decode("ascii")))

def render(data, out):
    head={};map_bytes=b"";his=None;cur=None;chg=None;vw=[];rooms=[];chains=[]
    off=0
    while off<len(data):
        fn,wt,val,off=dfield(data,off)
        if fn==3 and wt==2:
            hf=decode_fields(val)
            head={"sizeX":hf.get(2,360),"sizeY":hf.get(3,300),
                  "minX":hf.get(4,0.0),"minY":hf.get(5,0.0),
                  "maxX":hf.get(6,0.0),"maxY":hf.get(7,0.0),
                  "resolution":hf.get(8,0.05)}
        elif fn==4 and wt==2: map_bytes=val
        elif fn==6 and wt==2: his=val
        elif fn==7 and wt==2: chg=val
        elif fn==8 and wt==2: cur=val
        elif fn==9 and wt==2: vw.append(val)
        elif fn==12 and wt==2:
            rf=decode_fields(val); n=rf.get(2,b"")
            if isinstance(n,bytes): n=n.decode("utf-8",errors="replace")
            rooms.append({"roomId":rf.get(1,0),"name":str(n)})
        elif fn==14 and wt==2:
            cf=decode_fields(val); rid=cf.get(1)
            pts_raw=cf.get(2,[]); 
            if not isinstance(pts_raw,list): pts_raw=[pts_raw]
            pts=[]
            for ptb in pts_raw:
                if isinstance(ptb,bytes):
                    pf=decode_fields(ptb); x=pf.get(1,0); y=pf.get(2,0)
                    if x<65536 and y<65536: pts.append((x,y))
            if rid and len(pts)>=3: chains.append({"roomId":rid,"points":pts})

    sx,sy=head["sizeX"],head["sizeY"]
    if not sx or not sy or not map_bytes: return

    pixels=map_bytes
    if pixels and pixels[0]==0x0a:
        length,hdr=varint(pixels,1)
        pixels=pixels[1+hdr:1+hdr+length]

    rnames={r["roomId"]:r["name"] for r in rooms}
    masks={}
    for c in chains:
        if len(c["points"])<3: continue
        masks[c["roomId"]]=[(x,sy-1-y) for x,y in c["points"] if x<sx and y<sy]

    pal=[(255,180,100),(100,200,255),(100,220,140),(255,200,80),
         (200,120,255),(255,140,180),(80,220,220),(240,230,100),
         (120,180,240),(160,230,120),(200,160,255),(255,180,120),
         (100,230,200),(230,220,160),(255,150,150),(150,200,255)]
    wall=(65,65,65); bg=(195,195,195)

    img=Image.new("RGB",(sx,sy),bg)
    draw=ImageDraw.Draw(img)
    for rid,poly in masks.items(): draw.polygon(poly,fill=pal[rid%len(pal)])

    px=img.load()
    for y in range(sy):
        for x in range(sx):
            idx=(sy-1-y)*sx+x
            if idx>=len(pixels): break
            v=pixels[idx]
            if v>127: v-=256
            if v<0: px[x,y]=wall
            elif v>0:
                b=px[x,y]; px[x,y]=tuple(int(c*0.88) for c in b)

    img=img.resize((sx*SCALE,sy*SCALE),Image.NEAREST)
    draw=ImageDraw.Draw(img); S=SCALE

    # forbidden areas
    ov=Image.new("RGBA",img.size,(0,0,0,0))
    dov=ImageDraw.Draw(ov)
    for w in vw:
        pts=get_points_list(w)
        if len(pts)<2: continue
        pp=[(int((p[0]-head["minX"])/head["resolution"]),
             int((sy-1-(p[1]-head["minY"])/head["resolution"]))) for p in pts]
        pp=[(x*S,y*S) for x,y in pp]
        if len(pp)>=3:
            dov.polygon(pp,fill=(255,180,180,60))
            dl=12*S
            for i in range(len(pp)):
                j=(i+1)%len(pp); x1,y1=pp[i];x2,y2=pp[j]
                segs=max(int(((x2-x1)**2+(y2-y1)**2)**0.5/dl),6)
                for k in range(0,segs,2):
                    t1=k/segs;t2=min(k+1,segs)/segs
                    draw.line([(x1+(x2-x1)*t1,y1+(y2-y1)*t1),
                              (x1+(x2-x1)*t2,y1+(y2-y1)*t2)],
                             fill=(220,40,40),width=max(2,S))
        else: draw.line(pp,fill=(220,40,40),width=max(2,S))
    img=Image.alpha_composite(img.convert("RGBA"),ov).convert("RGB")
    draw=ImageDraw.Draw(img)

    # cleanning tracks
    if his:
        o=0
        pp=[]
        while o<len(his):
            fn,wt,val,o=dfield(his,o)
            if fn==2 and wt==2:
                pf=decode_fields(val)
                if pf.get(1,0)==1:
                    wx=pf.get(2,0.0);wy=pf.get(3,0.0)
                    pp.append((int((wx-head["minX"])/head["resolution"]),
                               int((sy-1-(wy-head["minY"])/head["resolution"]))))
        if len(pp)>1:
            pp=[(x*S,y*S) for x,y in pp]
            draw.line(pp,fill=(255,255,255),width=max(1,S//2))

    # charger
    if chg:
        cf=decode_fields(chg)
        cx=cf.get(1,0.0); cy=cf.get(2,0.0)
        if isinstance(cx,list):cx=cx[0]
        if isinstance(cy,list):cy=cy[0]
        pc=int((cx-head["minX"])/head["resolution"]); py_c=int((cy-head["minY"])/head["resolution"])
        py_c=sy-1-py_c;r=6*S
        draw.ellipse([pc*S-r,py_c*S-r,pc*S+r,py_c*S+r],fill=(0,200,0),outline=(0,255,0))

    # bot
    if cur:
        pf=decode_fields(cur)
        rx=pf.get(3,0.0);ry=pf.get(4,0.0);phi=pf.get(5,0.0)
        for v in [rx,ry,phi]:
            if isinstance(v,list):v=v[0]
        pr=int((rx-head["minX"])/head["resolution"]); py_r=int((ry-head["minY"])/head["resolution"])
        py_r=sy-1-py_r;px_s,py_s=pr*S,py_r*S;r=7*S
        draw.ellipse([px_s-r,py_s-r,px_s+r,py_s+r],fill=(0,120,255),outline=(0,200,255))
        ax=px_s+int(r*2.5*math.cos(phi)); ay=py_s+int(r*2.5*math.sin(phi))
        draw.line([(px_s,py_s),(ax,ay)],fill=(255,255,255),width=max(2,3*S))

    # room name
    try: font=ImageFont.truetype("C:\\Windows\\Fonts\\msyhbd.ttc",9*S)
    except:
        try: font=ImageFont.truetype("C:\\Windows\\Fonts\\msyh.ttc",9*S)
        except: font=ImageFont.load_default()
    for c in chains:
        rid=c["roomId"];nm=rnames.get(rid,"")
        if not nm or len(c["points"])<3: continue
        xs=[p[0] for p in c["points"]];ys=[p[1] for p in c["points"]]
        cx_t=(max(xs)+min(xs))//2*S;cy_t=(sy-1-(max(ys)+min(ys))//2)*S
        draw.text((cx_t,cy_t),nm,fill=(30,30,30),font=font,anchor="mm")

    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    img.save(out)
    return True

# === main loop ===
print("[*] live map (fetch every 2 sec)")
print("    Ctrl+C stop\n")
frame = 0
while True:
    try:
        t0 = time.time()
        url = api("/v2/home/get_interim_file_url_pro", {"obj_name": f"{UID}/{DID}/0"})
        if url:
            raw = download(url)
            pb = decrypt(raw)
            render(pb, OUT)
            frame += 1
            print(f"  [{time.strftime('%H:%M:%S')}] Frame {frame} OK")
        else:
            print(f"  [{time.strftime('%H:%M:%S')}] No URL")
    except KeyboardInterrupt:
        print("\n[*] stop")
        break
    except Exception as e:
        print(f"  [!] {e}")
    elapsed = time.time() - t0
    time.sleep(max(0, 2 - elapsed))
```

**Comment by wanderer1983** [comment]
can you explain how to integrate this in so we finally can get the maps working?

**Comment by TheSnowfield** [comment]
> can you explain how to integrate this in so we finally can get the maps working?

I will PR to this project if I have time in recently

Current my workaround is hass-miot + mushroom(with modified vacuum card)
hass-miot decodes the protobuf, AES-ECB, and creates an sensor entity which contains full data for renderering the map in the frontend(mushroom)

<img width="527" height="541" alt="Image" src="https://github.com/user-attachments/assets/cbf00f68-07c6-4a90-ae4a-3e2a74e2bdb8" />

## technical informations
you can send my script file to chatGPT then analyze it. and some useful informations based on reverse-engineering

Upload flow
```
protobuf → zlib compress → hex encoding → AES-ECB → base64 → KS3
```

Download flow
```
KS3 → AES-ECB  → hex decoding → zlib decompress → protobuf
```
 
**SCCMapColor encoding**

| value | explain |
|--------|------|
| -1 | wall |
| -30 | test |
| -9 | obstacle |
| -4 | patch_carpet |
| -3 | carpet |
| -2 | patch |
| 0 | background (non-disconver) |
| 1 | discover|
| 2 | cover |
| 3 | deepCover |
| 10~59 | roomBegin-roomEnd (roomId=value) |
| 60~109 | coverRoomBegin-coverRoomEnd (roomId=value-50) |
| -109~-60 | deepCoverRoomBegin-deepCoverRoomEnd (roomId=-value-50) |
| 127 | clearedArea|
| -128 (unsigned 128) | / |

**Comment by TheSnowfield** [comment]
mijia plugin
[xiaomi.vacuum.c101.1037113.zip](https://github.com/user-attachments/files/29299866/xiaomi.vacuum.c101.1037113.zip)
