### ISSUE TITLE
Request new Vacuum Mijia Robot Vacuum M30 Pro

### ISSUE THREAD

**Issue by GwangGyuChoi** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#523]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the vacuum/platform is already requested
- [ ] I have sent raw map file to `piotr.machowski.dev [at] gmail.com` ([Retrieving map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map); please provide your GitHub username in the email)

### What vacuum model do you want to be supported?

Mijia Robot Vacuum M30 Pro

### What is its name?

xiaomi.vacuum.c107

### Available APIs

- [X] xiaomi
- [ ] viomi
- [ ] roidmi
- [ ] dreame

### Errors shown in the HA logs (if applicable)

```shell
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:945
First occurred: 오후 11:25:14 (50 occurrences)
Last logged: 오후 11:33:09

Update for camera.xiaomi_cloud_map_extractor fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1264, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 278, in update
    self._handle_map_data(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 335, in _handle_map_data
    map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 27, in get_map
    response = self.get_raw_map_data(map_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 45, in get_raw_map_data
    map_url = self.get_map_url(map_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum_v2.py", line 18, in get_map_url
    if api_response is None or "result" not in api_response or "url" not in api_response["result"]:
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by Elphman** [comment]
Waiting for this one as well. Let me know if i can help with beer to motivate you :)

**Comment by pruwait** [comment]
Need xiaomi.vacuum.c107 too...

**Comment by kostrum** [comment]
waiting for xiaomi.vacuum.c107 as well

**Comment by kostrum** [comment]
![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/60359942/4ba73acd-2a98-4f4d-9b56-4dfc8d5fedae)
I have such error.
Is it possible to fix?

**Comment by lcapelo** [comment]
I have the same issue.

Need xiaomi.vacuum.c107 too.

**Comment by GalaxyGiant** [comment]
I can use the Xiaomi Home app to check map.
What can I do for you?

![Image](https://github.com/user-attachments/assets/ffdc6b29-3ec2-4249-957a-c60ece24a045)
