### ISSUE TITLE
Exceptions in log when Vacuum is in an error state

### ISSUE THREAD

**Issue by dlashua** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#53]
My vacuum (Roborock S5) was running and I picked it up off the ground. This resulted in the following errors in the Home Assistant log until I put it down again and resumed the cleaning.

```
2020-12-05 08:24:35 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.sofie fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 190, in update
    map_data = self._connector.get_map(self._country, map_name, self._colors, self._drawables, self._texts,
  File "/config/custom_components/xiaomi_cloud_map_extractor/xiaomi_cloud_connector.py", line 113, in get_map
    response = self.get_raw_map_data(country, map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/xiaomi_cloud_connector.py", line 124, in get_raw_map_data
    map_url = self.get_map_url(country, map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/xiaomi_cloud_connector.py", line 110, in get_map_url
    return api_response["result"]["url"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by PiotrMachowski** [comment]
That's interesting :) I have to check it out

**Comment by dlashua** [comment]
Thanks!

It's worth mentioning, the Exception didn't HURT anything. Once I set the vacuum back down, it picked up where it left off just fine with no issues. So, this is more of an annoyance than an issue.
