### ISSUE TITLE
Invalid calibration, please check your configuration

### ISSUE THREAD

**Issue by KoalaMontana** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#550]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Hello! I recently started getting to know the Home Assistant. Could you help me set up my robot [Viomi V5 Pro](https://home.miot-spec.com/spec/viomi.vacuum.v38)? No matter what options I try, I always get a message about an incorrect calibration.
I saw the [configuration](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/251#issuecomment-1152191859) option for my device, but when I try to add it I get the message "Invalid template: vacuum_goto". I don't understand what's going on.

Card config
`type: custom:xiaomi-vacuum-map-card
entity: vacuum.viomi_v38_150f_robot_cleaner
map_source:
  camera: camera.xiaomi_cloud_map_extractor
vacuum_platform: al-one/hass-xiaomi-miot
calibration_source:
  camera: true
camera_calibration: true`

### What version of an integration has described problem?

v2.2.0

### What vacuum model do you have problems with?

viomi.vacuum.v38 

### What version of Home Assistant do you use?

2024.8.2

### What type of installation are you running?

Home Assistant Supervised

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ["all"]
    attributes:
      - calibration_points
    auto_update: false
```

### Errors shown in the HA logs (if applicable)

```shell
2024-08-19 15:37:27.491 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration vacuum_zones which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-08-19 15:37:27.495 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_cloud_map_extractor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-08-19 15:37:27.499 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration yandex_station which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-08-19 15:37:27.502 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-08-19 15:37:27.504 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration yandex_smart_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-08-19 15:37:27.505 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-08-19 15:37:27.510 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-08-19 15:37:32.593 WARNING (ImportExecutor_0) [homeassistant.components.camera] SUPPORT_ON_OFF was used from xiaomi_cloud_map_extractor, this is a deprecated constant which will be removed in HA Core 2025.1. Use CameraEntityFeature.ON_OFF instead, please report it to the author of the 'xiaomi_cloud_map_extractor' custom integration
2024-08-19 15:37:32.598 WARNING (ImportExecutor_0) [homeassistant.components.camera] SUPPORT_ON_OFF was used from xiaomi_cloud_map_extractor, this is a deprecated constant which will be removed in HA Core 2025.1. Use CameraEntityFeature.ON_OFF instead, please report it to the author of the 'xiaomi_cloud_map_extractor' custom integration
2024-08-19 15:37:32.702 WARNING (MainThread) [homeassistant.helpers.entity] Entity camera.xiaomi_cloud_map_extractor (<class 'custom_components.xiaomi_cloud_map_extractor.camera.VacuumCamera'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <CameraEntityFeature.ON_OFF: 1>, please create a bug report at https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-08-19 15:37:36.134 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles/frontend", "/config/custom_components/hacs/hacs_frontend_experimental", False)])`; This function will be removed in 2025.7 at custom_components/hacs/frontend.py, line 49: hass.http.register_static_path(, please create a bug report at https://github.com/hacs/integration/issues
2024-08-19 15:37:36.150 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles/iconset.js", "/config/custom_components/hacs/iconset.js", True)])`; This function will be removed in 2025.7 at custom_components/hacs/frontend.py, line 57: hass.http.register_static_path(, please create a bug report at https://github.com/hacs/integration/issues
2024-08-19 15:37:36.164 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
2024-08-19 15:37:36.180 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles", "/config/www/community", True)])`; This function will be removed in 2025.7 at custom_components/hacs/base.py, line 1162: self.hass.http.register_static_path(, please create a bug report at https://github.com/hacs/integration/issues
2024-08-19 15:37:37.989 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from yandex_station, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'yandex_station' custom integration
2024-08-19 15:37:38.517 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] CURRENT_HVAC_HEAT was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.HEATING instead, please report it to the author of the 'localtuya' custom integration
2024-08-19 15:37:38.555 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] CURRENT_HVAC_IDLE was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.IDLE instead, please report it to the author of the 'localtuya' custom integration
2024-08-19 15:37:38.578 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_AUTO was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.AUTO instead, please report it to the author of the 'localtuya' custom integration
2024-08-19 15:37:38.598 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_HEAT was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please report it to the author of the 'localtuya' custom integration
2024-08-19 15:37:38.560 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.xiaomi_cloud_map_extractor fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 278, in update
    self._handle_map_data(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 335, in _handle_map_data
    map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 36, in get_map
    map_data = self.decode_map(response, colors, drawables, texts, sizes, image_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/viomi/vacuum.py", line 22, in decode_map
    unzipped = zlib.decompress(raw_map)
               ^^^^^^^^^^^^^^^^^^^^^^^^
zlib.error: Error -3 while decompressing data: incorrect header check
2024-08-19 15:37:38.635 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_OFF was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please report it to the author of the 'localtuya' custom integration
2024-08-19 15:37:38.661 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] SUPPORT_PRESET_MODE was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.PRESET_MODE instead, please report it to the author of the 'localtuya' custom integration
2024-08-19 15:37:38.679 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] SUPPORT_TARGET_TEMPERATURE was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please report it to the author of the 'localtuya' custom integration
2024-08-19 15:37:38.697 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] SUPPORT_TARGET_TEMPERATURE_RANGE was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE_RANGE instead, please report it to the author of the 'localtuya' custom integration
2024-08-19 15:37:38.713 WARNING (ImportExecutor_0) [homeassistant.const] TEMP_CELSIUS was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'localtuya' custom integration
2024-08-19 15:37:38.743 WARNING (ImportExecutor_0) [homeassistant.const] TEMP_FAHRENHEIT was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.FAHRENHEIT instead, please report it to the author of the 'localtuya' custom integration
2024-08-19 15:37:38.768 WARNING (ImportExecutor_0) [homeassistant.components.cover] SUPPORT_CLOSE was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.CLOSE instead, please report it to the author of the 'localtuya' custom integration
2024-08-19 15:37:38.782 WARNING (ImportExecutor_0) [homeassistant.components.cover] SUPPORT_OPEN was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.OPEN instead, please report it to the author of the 'localtuya' custom integration
2024-08-19 15:37:38.802 WARNING (ImportExecutor_0) [homeassistant.components.cover] SUPPORT_SET_POSITION was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.SET_POSITION instead, please report it to the author of the 'localtuya' custom integration
2024-08-19 15:37:38.819 WARNING (ImportExecutor_0) [homeassistant.components.cover] SUPPORT_STOP was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.STOP instead, please report it to the author of the 'localtuya' custom integration
2024-08-19 15:37:38.832 WARNING (ImportExecutor_0) [homeassistant.components.cover] SUPPORT_CLOSE was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.CLOSE instead, please report it to the author of the 'localtuya' custom integration
2024-08-19 15:37:38.850 WARNING (ImportExecutor_0) [homeassistant.components.cover] SUPPORT_OPEN was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.OPEN instead, please report it to the author of the 'localtuya' custom integration
2024-08-19 15:37:38.863 WARNING (ImportExecutor_0) [homeassistant.components.cover] SUPPORT_SET_POSITION was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.SET_POSITION instead, please report it to the author of the 'localtuya' custom integration
2024-08-19 15:37:38.875 WARNING (ImportExecutor_0) [homeassistant.components.cover] SUPPORT_STOP was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.STOP instead, please report it to the author of the 'localtuya' custom integration
2024-08-19 15:37:38.891 WARNING (ImportExecutor_0) [homeassistant.components.fan] SUPPORT_DIRECTION was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.DIRECTION instead, please report it to the author of the 'localtuya' custom integration
2024-08-19 15:37:38.902 WARNING (ImportExecutor_0) [homeassistant.components.fan] SUPPORT_OSCILLATE was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.OSCILLATE instead, please report it to the author of the 'localtuya' custom integration
2024-08-19 15:37:38.920 WARNING (ImportExecutor_0) [homeassistant.components.fan] SUPPORT_SET_SPEED was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.SET_SPEED instead, please report it to the author of the 'localtuya' custom integration
2024-08-19 15:37:38.964 WARNING (ImportExecutor_0) [homeassistant.components.fan] SUPPORT_DIRECTION was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.DIRECTION instead, please report it to the author of the 'localtuya' custom integration
2024-08-19 15:37:38.989 WARNING (ImportExecutor_0) [homeassistant.components.fan] SUPPORT_OSCILLATE was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.OSCILLATE instead, please report it to the author of the 'localtuya' custom integration
2024-08-19 15:37:39.017 WARNING (ImportExecutor_0) [homeassistant.components.fan] SUPPORT_SET_SPEED was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.SET_SPEED instead, please report it to the author of the 'localtuya' custom integration
2024-08-19 15:37:39.595 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'localtuya' accesses hass.helpers.service. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from service directly at custom_components/localtuya/__init__.py, line 164: hass.helpers.service.async_register_admin_service(, please create a bug report at https://github.com/rospogrigio/localtuya/issues
2024-08-19 15:37:41.216 WARNING (MainThread) [custom_components.xiaomi_miot.sensor] Get xiaomi scene history for 1578680829 5707 failed: {'code': 0, 'message': '成功', 'result': {'history': []}}
```

### Additional information

Please ask me if you need any further information.

**Comment by Bramw2003** [comment]
Having the same problem

**Comment by KoalaMontana** [comment]
@Bramw2003 I managed to get a map and a room with this configuration:
```yaml
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw:
      - charger
      - cleaned_area
      - goto_path
      - ignored_obstacles
      - ignored_obstacles_with_photo
      - no_go_zones
      - no_mopping_zones
      - obstacles
      - obstacles_with_photo
      - path
      - predicted_path
      - vacuum_position
      - virtual_walls
      - zones
    attributes:
      - calibration_points
      - rooms
    force_api: roidmi
    scan_interval:
        seconds: 60
    auto_update: true
    store_map_raw: false
    store_map_image: true
    store_map_path: "/tmp"
```

But I still have a problem with starting the vacuum cleaner by rooms and zones - no matter what I select, it starts a full cleaning instead of the selected zone. Obviously, I need help with selecting digital values (SIID, PIID, AIID, e.t.c.).

**Comment by aliguzel0** [comment]
I have the same problem. My viomi alpha 2 pro device is being controlled. But the map is not coming... Please help.

**Comment by KoalaMontana** [comment]
@aliguzel0 Have you tried my config? Did you remember to reboot after changing the config?

**Comment by Bramw2003** [comment]
I had no errors with your config just a camera saying it couldn't fetch the map. Using a Xiaomi X10.

**Comment by pinkfloydFR** [comment]
Same here, nothing change on my configuration since a long time and today i see this message :(

**Comment by rbsoliveira89** [comment]
> I have the same problem. My viomi alpha 2 pro device is being controlled. But the map is not coming... Please help.

did you solve it? i have a alpha 2 pro

**Comment by PiotrMachowski** [comment]
Fixed in [v2.2.2](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/releases/tag/v2.2.2)

**Comment by mclwill** [comment]
I am getting this error after update of HA to 2025.7.2 today.

I have attached a sample of the repeated errors that are being logged.

[2025-07-15 Robot Vacuum.txt](https://github.com/user-attachments/files/21224919/2025-07-15.Robot.Vacuum.txt)

**Comment by JaCh0o** [comment]
Hello Mr @PiotrMachowski ,
 same issue here i got Roborck S8 Pro Ultra. On my setup i sue Roborock app on phone (so dont have Xiaomi App - cant extract token from there - so can't use [Xiaomi Cloud Token Extractor](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor)) and got two maps (Piętro and Parter) - on both i get error: "Nieprawidłowa kalibracja, sprawdź konfigurację"
I've already installed: Xiaomi Vacuum Map Card, Roborock Offical Integration and Roborock Custom Map.
My card configuration:
```
type: custom:xiaomi-vacuum-map-card
vacuum_platform: Roborock
entity: vacuum.s8_pro_ultra
map_source:
  camera: image.r2d2_parter
calibration_source:
  camera: true
title: Parter
```
Im not sure do i need map card extractor after those 2025.4 upgrade and Roborock integration. May i ask what am i missing here ??

**Comment by PiotrMachowski** [comment]
@JaCh0o well, first thing first, you should ask this question in the card repo, not here 😉 

You shouldn't use Map Extractor, you should:
1. Configure built-in Roborock integration 
2. Download and configure [this custom integration](https://github.com/Lash-L/RoborockCustomMap/)
3. Use the image entity from the custom integration
