### ISSUE TITLE
Add suport for Xiaomi Robot Vacuum X20+

### ISSUE THREAD

**Issue by alx6ths** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#558]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the vacuum/platform is already requested
- [ ] I have sent raw map file to `piotr.machowski.dev [at] gmail.com` ([Retrieving map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map); please provide your GitHub username in the email)

### What vacuum model do you want to be supported?

xiaomi.vacuum.c102gl

### What is its name?

Xiaomi Robot Vacuum X20+

### Available APIs

- [ ] xiaomi
- [ ] viomi
- [ ] roidmi
- [ ] dreame

**Comment by javato** [comment]
you are not alone at this war my friend.

I haven't managed to make it work on Xiaomi X20+

**Comment by Matssa56** [comment]
Same on my S20+

**Comment by virnik0** [comment]
> Same on my S20+

Same here with S20

Vacuum works fine, even [hass-xiaomi-miot](https://github.com/al-one/hass-xiaomi-miot) works as it should, but thanks to extractor not working, I have no map/camera. Config is ok. But my problem is that it spews bellow error:
`TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'`

and camera is in Idle state with no picture. Looks like my model is not supported. What a shame

**Comment by Nicooow** [comment]
maybe this integration will also be solved with https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues/460 (_it seems to be all the same for xiaomi.vacuum.XXX_)

**Comment by virnik0** [comment]
> maybe this integration will also be solved with #460 (_it seems to be all the same for xiaomi.vacuum.XXX_)

Nope. Tested, and complains about decode message. I do receive "Passed" in chinese letters as an api reply, but no map.
Scene download also fails.

**Comment by Schmarni** [comment]
I have the same Problem with the x20+ Model c102gl.
![Uploading IMG_0288.jpeg…]()

**Comment by Jaggana69** [comment]
Hello,

Quick updated, I've tried everything but can't get map for my X20+, even with Dreame Vacuum
Does anyone has a solution?

**Comment by Tasshack** [comment]
> Hello,
> 
> Quick updated, I've tried everything but can't get map for my X20+, even with Dreame Vacuum Does anyone has a solution?

You need to install the latest Beta version of Dreame Vacuum since Mi Cloud has added 2fa login requirement.

**Comment by Jaggana69** [comment]
> > Hello,
> > Quick updated, I've tried everything but can't get map for my X20+, even with Dreame Vacuum Does anyone has a solution?
> 
> You need to install the latest Beta version of Dreame Vacuum since Mi Cloud has added 2fa login requirement.

I'm terribly sorry, I thought I had it but how the dropdown version selection was shown I thought I already had the last Beta, but not...
Thanks a looooot <3

**Comment by ghostmaster75** [comment]
news about this integration?

**Comment by PiotrMachowski** [comment]
At this moment all the development happens on the [dev_extracted_libraries](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/tree/dev_extracted_libraries) branch

**Comment by panoskpv** [comment]
Any news on the support of x20+? I can use only xiaomi miot which is limited

**Comment by Schmarni** [comment]
@panoskpv 
Have you tried connecting the x20+ via the Dreame integration? It works perfectly for me.
Or is there a specific reason to use Xiaomi Miot?

**Comment by panoskpv** [comment]
@Schmarni 
I have tried to connect it however I get error that no compatible devices were found on the server I am connected. Did you have this issue initially or you connected without issues? I recently purchased the vacuum so I am worried that they have changed something in the newer versions or even manufacturer causing issues.

**Comment by ghostmaster75** [comment]
> [@panoskpv](https://github.com/panoskpv) Have you tried connecting the x20+ via the Dreame integration? It works perfectly for me. Or is there a specific reason to use Xiaomi Miot?

with my  xiaomi.vacuum.c102gl i have the same issue with map extractor.  And dreame not find any compatible device. 

I also tried reverse engineering the Xiaomi Home app and the libmio.so library, which I believe is responsible for encrypting and decrypting the map data, but without any success. The only thing I (maybe) figured out is that the device token seems to be involved in the encryption, but I wasn’t able to find the exact way to decrypt the data

**Comment by Tasshack** [comment]
Just install the Beta version of dreame_vacuum.

**Comment by panoskpv** [comment]
> Just install the Beta version of dreame_vacuum.

I am using the latest beta

**Comment by janvda** [comment]
I am having X20+ and I am using version v3.0.0-beta and it is not working for me:

<img width="976" height="337" alt="Image" src="https://github.com/user-attachments/assets/04bc8b6d-d1e3-438b-91f2-59451770a64a" />


```
2025-12-28 16:57:35.294 WARNING (MainThread) [miio.miot_device] Unable to find mapping for xiaomi.vacuum.c102gl, falling back to dreame.vacuum.mc1808
2025-12-28 16:57:35.424 ERROR (MainThread) [custom_components.xiaomi_cloud_map_extractor.coordinator] Unexpected error fetching xiaomi_cloud_map_extractor data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 419, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 308, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/coordinator.py", line 36, in update_data
    return await self.connector.get_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/connector/__init__.py", line 77, in get_data
    await self._get_map()
  File "/config/custom_components/xiaomi_cloud_map_extractor/connector/__init__.py", line 138, in _get_map
    await self._update()
  File "/config/custom_components/xiaomi_cloud_map_extractor/connector/__init__.py", line 106, in _update
    map_data, map_saved, map_raw_data = await self._vacuum_connector.get_map()
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/connector/vacuums/base/vacuum_base.py", line 91, in get_map
    map_data = self.decode_and_parse(raw_map_data)
  File "/config/custom_components/xiaomi_cloud_map_extractor/connector/vacuums/vacuum_dreame.py", line 49, in decode_and_parse
    decoded_map = self.map_data_parser.unpack_map(raw_map, enckey=self._enc_key)
  File "/usr/local/lib/python3.13/site-packages/vacuum_map_parser_dreame/map_data_parser.py", line 91, in unpack_map
    unzipped = zlib.decompress(raw_map)
zlib.error: Error -3 while decompressing data: incorrect header check
```

**Comment by janvda** [comment]
> Just install the Beta version of dreame_vacuum.

It took me some time to understand that *dreame_vacuum* is actually a different integration (https://github.com/Tasshack/dreame-vacuum)

**Work Around:** 
If you want to be able to see the map in home-assistant for Xiaomi X20+ then you have to install the beta version of [Dreame Vacuum](https://github.com/Tasshack/dreame-vacuum) integration
I got it working with version Version v2.0.0b21 (still need to do some configuration).

**Comment by PeterPin71** [comment]
I simply cannot get the map to load for my vacuum cleaner: vacuum.xiaomi_c102gl_9ea4_robot_cleaner. It's not working no matter what I try. Here is my log output for troubleshooting:

[home-assistant_xiaomi_cloud_map_extractor_2026-02-20T08-20-49.159Z.log](https://github.com/user-attachments/files/25461438/home-assistant_xiaomi_cloud_map_extractor_2026-02-20T08-20-49.159Z.log)

**Comment by AldenDana** [comment]
Possibly useful for unblocking the `xiaomi.vacuum.*` family (mine is a **d102gl / X20 Pro**, EU server):

**The download route for these models is the undocumented `/v2/home/get_interim_file_url_pro` endpoint.** The endpoints the integration currently uses both fail for this family — `/home/getmapfileurl` returns `code -8 objectname invalid` and `/v2/home/get_interim_file_url` returns `code -6 invalid config for fds` — because these models store maps in **per-model FDS buckets** (the signed URL returned by `_pro` points at `https://awsde0-fusion.fds.api.xiaomi.com/xiaomi-d102gl/...`).

- Request: `{"obj_name": "<userId>/<did>/<slot>"}` — obj names come from the vacuum's miot properties `map_obj_name`, `trajectory_obj_name` and `map_management.map_array[].obj_name`.
- Response file: JSON `{"version": 2, "data": "<base64>"}`. The decoded payload is high-entropy from byte 0 (not zlib/gzip/lz4-frame), so it looks **encrypted** — that part I haven't cracked.

I've published 4 raw samples (map slots 0/2/4/8) with known ground truth (8 rooms with known miot ids, a known zone rectangle in map coordinates, restricted areas + furniture polygons from entity attributes for cross-referencing) here: https://github.com/AldenDana/ha-xiaomi-vacuum-x20pro/tree/master/docs/map-samples

Happy to email the samples as well or capture more (e.g. before/after moving a no-go zone) if that helps.

**Comment by AlexanderDyom** [comment]
Update — working on [Dreame Vacuum](https://github.com/Tasshack/dreame-vacuum) v2.0.0b25 for me (model xiaomi.vacuum.c102gl)

With Xiaomi Miot integration: 28 entities, no map.
With Dreame Vacuum v2.0.0b25: 115 entities, including a working map.
