### ISSUE TITLE
Not load map from roidmi.vacuum.sdj60

### ISSUE THREAD

**Issue by Splintergreen** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#572]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Can't load map from my roidmi.vacuum.sdj60
![image](https://github.com/user-attachments/assets/ba7bf24d-3f1c-4ce9-b834-30a1cda80d50)

### What version of an integration has described problem?

v2.2.1

### What vacuum model do you have problems with?

roidmi.vacuum.sdj60

### What version of Home Assistant do you use?

2023.5.2

### What type of installation are you running?

Home Assistant Container

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    force_api: xiaomi
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
      - rooms
```

### Errors shown in the HA logs (if applicable)

```shell
With force_api: xiaomi i have error:

2024-12-11 21:32:02.180 ERROR (MainThread) [custom_components.xiaomi_miot.vacuum] ROIDMI EVE MAX(roidmi.vacuum.sdj60): Got MiioException while fetching the state: No response from the device, mapping: {'vacuum.status': {'siid': 2, 'piid': 1}, 'vacuum.fault': {'siid': 2, 'piid': 2}, 'vacuum.mode': {'siid': 2, 'piid': 4}, 'sweep.sweep_mode': {'siid': 14, 'piid': 1}, 'map.clean_path': {'siid': 13, 'piid': 1}, 'map.multi_maps_info': {'siid': 13, 'piid': 6}, 'brush_left_time-16-1': {'siid': 16, 'piid': 1}, 'brush_life_level-16-2': {'siid': 16, 'piid': 2}, 'mop-15.mop_life_level': {'siid': 15, 'piid': 1}, 'mop-15.mop_left_time': {'siid': 15, 'piid': 2}, 'brush_left_time-12-1': {'siid': 12, 'piid': 1}, 'brush_life_level-12-2': {'siid': 12, 'piid': 2}, 'brush_cleaner.brush_left_time': {'siid': 11, 'piid': 1}, 'brush_cleaner.brush_life_level': {'siid': 11, 'piid': 2}, 'speaker.volume': {'siid': 10, 'piid': 2}, 'mop.mop_life_level': {'siid': 9, 'piid': 1}, 'mop.mop_left_time': {'siid': 9, 'piid': 2}, 'battery_level': {'siid': 3, 'piid': 1}}, max_properties: 9/18

With other force_api:
2024-12-11 21:36:15.027 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.xiaomi_cloud_map_extractor fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 554, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in async_device_update
    await coro
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 278, in update
    self._handle_map_data(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 335, in _handle_map_data
    map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 27, in get_map
    response = self.get_raw_map_data(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 45, in get_raw_map_data
    map_url = self.get_map_url(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum_v2.py", line 18, in get_map_url
    if api_response is None or "result" not in api_response or "url" not in api_response["result"]:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by Splintergreen** [comment]
After upgrading to the latest versions of HA,Xiaomi Miot Auto, Xiaomi Cloud Map Extractor.
Current version: HA 2025.1.1, Xiaomi Miot Auto 1.0.8, Xiaomi Cloud Map Extractor 2.2.3
If I use force_api: xiaomi, I get endless delays and a timeout when loading the card.
`2025-01-07 20:50:37.807 ERROR (SyncWorker_2) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2025-01-07 20:50:37.808 WARNING (SyncWorker_2) [custom_components.xiaomi_cloud_map_extractor.camera] Got exception while fetching the state: Unable to recover failed command
2025-01-07 20:50:38.876 DEBUG (SyncWorker_2) [custom_components.xiaomi_cloud_map_extractor.camera] Asking device for map name... (10/10)
2025-01-07 20:50:55.097 ERROR (SyncWorker_2) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2025-01-07 20:50:55.098 WARNING (SyncWorker_2) [custom_components.xiaomi_cloud_map_extractor.camera] Got exception while fetching the state: Unable to recover failed command`
If I use force_api: roidmi, I get an error:
`2025-01-09 11:13:43.593 DEBUG (SyncWorker_1) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map from Xiaomi cloud
2025-01-09 11:13:43.774 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.xiaomi_cloud_map_extractor fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 960, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1320, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 291, in update
    self._handle_map_data(self._map_name)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 362, in _handle_map_data
    map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
                           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                self._sizes, self._image_config, store_map_path)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 27, in get_map
    response = self.get_raw_map_data(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 45, in get_raw_map_data
    map_url = self.get_map_url(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum_v2.py", line 18, in get_map_url
    if api_response is None or "result" not in api_response or "url" not in api_response["result"]:
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable`

**Comment by horinka-gabor** [comment]
Same here.

**Comment by winchester7** [comment]
Same problem. Sniffed requests from my app. Now app using new url '/v2/home/get_interim_file_url_pro'.

After change url got error:
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 960, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1320, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 291, in update
    self._handle_map_data(self._map_name)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 362, in _handle_map_data
    map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
                           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                self._sizes, self._image_config, store_map_path)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 36, in get_map
    map_data = self.decode_map(response, colors, drawables, texts, sizes, image_config)
  File "/config/custom_components/xiaomi_cloud_map_extractor/roidmi/vacuum.py", line 23, in decode_map
    return MapDataParserRoidmi.parse(unzipped, colors, drawables, texts, sizes, image_config)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/roidmi/map_data_parser.py", line 24, in parse
    width = map_info["width"]
            ~~~~~~~~^^^^^^^^^
TypeError: list indices must be integers or slices, not str`

I guess the format of the response has changed as well.

My raw data of map:
`
[1741109371,0,3700,-1110,0,0,52,12,392,12,-62,6,-22,-516,52,-26,52,26,72,16,502,-36,52,-26,42,-46,32,-66,12,-66,2,-546,182,-26,52,-26,52,-56,22,-66,52,-36,22,-66,2,-66,-32,-66,-32,-116,32,-56,-12,-116,22,-66,62,-106,42,-46,52,-16,112,46,62,-16,112,-26,52,36,62,6,62,-16,52,36,22,66,42,46,52,36,52,26,62,26,62,6,182,-26,32,46,12,196,22,56,42,56,52,36,62,26,362,56,62,-26,52,-36,52,-56,42,-46,32,46,-42,36,-62,26,-52,46,-22,56,-22,56,-52,16,-42,46,-62,16,-42,56,-22,66,2,66,32,66,42,56,52,26,-92,106,-32,56,-12,56,-62,-16,-72,6,-52,16,-62,-26,-52,-36,-72,-26,-62,-16,-332,36,-62,16,-52,46,-32,56,-32,126,-22,66,-22,66,2,66,72,496,-32,56,-12,66,2,56,-552,6,-62,16,-52,46,-42,56,-32,56,-22,116,-162,16,-52,26,-52,-16,-232,6,2,-116,-22,-66,-22,-66,-52,-46,-52,-46,-62,-26,-62,-16,-182,36,-22,-66,-12,-106,52,-13,432,148,592,18,-92,148,-52,38,-62,8,-182,-38,-122,8,-32,-53,-502,-258,52,18,1512,8,32,-48,12,-118,-1562,-28,-42,-28,2,-68,22,-58,1522,8,-42,-63,-82,-73,-52,-28,-642,-28,2,-68,12,-68,72,-18,712,8,32,-58,32,-108,-692,-18,-32,-48,-12,-68,42,-48,1622,8,22,-68,2,-58,-42,-48,-1612,-28,52,-28,42,-38,72,-88,62,-38,1382,28,42,-28,12,-118,-1442,-38,-22,-46,2,-64,62,13,52,3,52,-28,52,-18,932,-28,-12,-58,-12,-68,-42,-38,-702,-18,-52,-23,-52,-103,52,-38,442,8,-52,-38,-112,-138,-62,-28,-182,38,-32,43,192,953,182,163,42,23,112,-23,62,18,182,38,-22,-56,-52,-46,-62,-16,-62,-16,-172,36,-52,22,-1092,482,-2152,-22,-52,-42,-262,-282,-372,-3452,2,-54,-52,-16,-12,-116,-12,-76,-42,-56,-42,-36,-62,-46,-62,-16,-62,-16,-172,36,-52,36,-32,46,-72,16,-182,6,-22,-56,-12,-66,-32,-66,-52,-46,-62,-26,-62,-26,-62,6,-62,26,-52,36,-52,46,-32,56,-42,46,-1192,16,-112,26,-32,-56,-12,-56,-42,-56,-52,-46,-62,-16,-62,6,-52,26,-52,36,-42,46,-32,56,2,56,-192,6,-12,-56,2,-66,62,-36,32,-36,32,-66,12,-66,-12,-66,-22,-66,-52,-106,32,-186,-12,-66,-22,-56,32,-56,12,-76,-12,-56,-22,-66,12,-56,62,-46,42,-56,22,-66,-12,-66,-12,-66,-32,-56,-42,-56,-42,-26,52,-16,42,-56,22,-56,12,-76,-12,-66,42,-106,82,96,62,36,62,6,62,6,62,-26,52,-46,32,-56,32,-56,2,-66,-22,-66,-32,-66,-42,-46,-162,-106,-172,-56,-42,-106,32,-56,-22,-56,192,-36,122,6,112,56,62,26,62,-16,182,-36,92,166,52,46,62,16,62,6,62,-36,42,-46,12,-56,62,-26,62,26,62,6,52,16,62,-26,52,-36,42,-56,12,-66,-12,-66,-32,-66,-82,-86,72,-86,52,-26,242,26,122,6,42,46,32,46,12,56,-12,56,-42,26,-42,66,-12,66,2,66,22,66,42,56,52,46,52,26,62,16,72,-16,52,-36,52,-36,52,-26,232,-36,62,16,52,26,212,226,162,96,102,36,-22,46,-12,56,12,66,22,66,-112,66,-42,56,-32,56,-12,66,12,66,22,66,42,46,52,46,62,26,62,16,62,6,182,-56,362,-26,42,36,22,266,-112,66,-42,56,-32,56,-12,76,2,66,32,236,-12,366,-62,-36,-62,-26,-62,16,-62,26,-52,46,-32,56,-22,66,-12,66,2,66,32,56,72,116,-52,26,-112,6,-52,-38,-32,-48,-22,-58,2,-53,102,-133,-52,-38,-822,-28,32,-118,52,-28,902,-18,62,-108,52,-38,52,-18,-1042,-28,-52,13,-162,153,-52,23,-352,-23,-32,-43,2,-108,-1342,-18,-42,38,-32,58,-52,38,-122,28,1502,33,52,103,-62,38,-1262,13,2,-63,2,-63,32,-283,52,-38,2982,-18,22,-108,-32,-58,-3472,-18,-22,-58,-12,-58,32,-58,52,26,42,56,62,26,62,26,62,16,182,-46,1582,16,122,-36,52,-36,112,-76,32,-56,22,-56,2,-66,-22,-66,-52,-56,-52,-26,-182,-36,-62,26,-42,36,-132,6,-182,36,-1502,16,-52,26,-42,56,-32,56,-22,66,12,66,42,66,-22,-63,-22,-43,12,-53,12,-53,-22,-153,12,-63,22,-58,52,-18,1712,3,632,8,402,-18,-52,33,-372,123,52,-18,1142,28,-22,58,-82,88,-52,38,-62,8,-932,-38,-52,28,-12,118,1042,43,-52,13,-52,-13,-42,-43,-542,-578,-2362,-28,-142,-98,-172,-48,62,28,2592,-18,52,-28,52,-108,-42,-38,-752,-26,72,-86,32,-66,2,-66,-22,-56,-32,-66,-52,-46,-52,-36,-132,6,-62,16,-52,46,-32,56,-22,66,2,66,12,66,32,56,42,56,52,36,62,16,62,6,62,-26,62,-46,2,53,-22,53,-42,43,-222,-13,-52,-23,-32,-43,-42,-38,-1212,-28,2,-58,22,-68,62,-28,1082,8,2,-68,12,-68,-62,-38,-72,8,-1032,-18,-52,-33,-122,-118,302,-18,32,-58,-12,-58,-42,-48,-242,-18,32,53,382,103,102,13,52,33,52,13,62,3,52,-38,652,-23,-222,-148,-12,-78,12,-68,22,-108,32,-58,52,-38,122,8,-32,63,-92,133,-12,53,2,503,22,53,252,223,52,13,172,-23,282,-293,22,-53,-22,-63,-42,-103,52,-28,52,28,82,78,182,28,-192,18,-42,38,-42,118,392,18,-52,22,-602,142,-112,-12,-112,142,-52,12,-232,-252,-32,-42,-112,-282,-52,-22,-622,42,-52,2,-42,-42,-52,-12,-452,-52,32,62,232,252,22,52,-32,452,-32,42,-532,502,-12,52,22,222,82,72,52,18,52,8,53,20,43,40,63,0,723,-100,-13,-50,3,-50,-23,-60,-53,40,-83,80,-43,20,-63,-10,-43,-30,-23,-50,13,-50,163,20,53,-10,23,50,-13,50,-53,10,-133,-100,-53,-20,-163,10,-53,-20,-153,60,-63,-20,-43,-30,-103,10,-53,0,-33,-50,-13,-50,-53,-90,-23,-50,23,-50,53,-30,33,-50,3,-170,43,-170,43,-30,903,-60,-33,-40,-13,-110,23,-50,363,-570,53,-20,313,130,63,20,163,-10,43,30,63,10,233,0,53,10,453,140,43,-30,293,-280,53,-10,53,10,23,50,3,60,-33,50]
`
Now we need to figure out how to parse this data.

**Comment by winchester7** [comment]
> Has anyone managed to solve this problem?

I tried to use the code of MiHome application to understand how exactly the map is built. As far as I understood, the libMapBeautyJni.so library is responsible for this. I tried to disassemble it and understand what's going on. No results so far.
