### ISSUE TITLE
Map works, but errors in logs

### ISSUE THREAD

**Issue by suskozaver** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#576]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

The map is shown 
![image](https://github.com/user-attachments/assets/83e2258f-5129-4349-b583-68b8170488bf)

but there are errors in the error log (see logs).

The only way I got this working is with https://github.com/Tasshack/dreame-vacuum 

The card code:
```
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_robot_vacuum_s10_map
calibration_source:
  camera: true
entity: vacuum.dreame_r2211o_7dbc_robot_cleaner
vacuum_platform: Tasshack/dreame-vacuum
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_point
  - template: vacuum_clean_segment
```

I can't for the love of (random) god(s) glue this together how it actually works, but still got a ton of errors in my error log. 

Any ideas, clues, pointers?

### What version of an integration has described problem?

v2.2.1

### What vacuum model do you have problems with?

dreame.vacuum.r2211o

### What version of Home Assistant do you use?

2024.12.5

### What type of installation are you running?

Home Assistant Container

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
```

### Errors shown in the HA logs (if applicable)

```shell
2024-12-31 10:14:07 homeassistant  | 2024-12-31 10:14:07.259 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.xiaomi_cloud_map_extractor fails
2024-12-31 10:14:07 homeassistant  | Traceback (most recent call last):
2024-12-31 10:14:07 homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 960, in async_update_ha_state
2024-12-31 10:14:07 homeassistant  |     await self.async_device_update()
2024-12-31 10:14:07 homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1320, in async_device_update
2024-12-31 10:14:07 homeassistant  |     await hass.async_add_executor_job(self.update)
2024-12-31 10:14:07 homeassistant  |   File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
2024-12-31 10:14:07 homeassistant  |     result = self.fn(*self.args, **self.kwargs)
2024-12-31 10:14:07 homeassistant  |   File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 278, in update
2024-12-31 10:14:07 homeassistant  |     self._handle_map_data(map_name)
2024-12-31 10:14:07 homeassistant  |     ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
2024-12-31 10:14:07 homeassistant  |   File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 335, in _handle_map_data
2024-12-31 10:14:07 homeassistant  |     map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
2024-12-31 10:14:07 homeassistant  |                            ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-31 10:14:07 homeassistant  |                                                 self._sizes, self._image_config, store_map_path)
2024-12-31 10:14:07 homeassistant  |                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-31 10:14:07 homeassistant  |   File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 36, in get_map
2024-12-31 10:14:07 homeassistant  |     map_data = self.decode_map(response, colors, drawables, texts, sizes, image_config)
2024-12-31 10:14:07 homeassistant  |   File "/config/custom_components/xiaomi_cloud_map_extractor/dreame/vacuum.py", line 24, in decode_map
2024-12-31 10:14:07 homeassistant  |     return MapDataParserDreame.decode_map(raw_map_string, colors, drawables, texts, sizes, image_config)
2024-12-31 10:14:07 homeassistant  |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-31 10:14:07 homeassistant  |   File "/config/custom_components/xiaomi_cloud_map_extractor/dreame/map_data_parser.py", line 51, in decode_map
2024-12-31 10:14:07 homeassistant  |     unzipped = zlib.decompress(base64.decodebytes(raw_map_string.encode("utf8")))
2024-12-31 10:14:07 homeassistant  | zlib.error: Error -3 while decompressing data: incorrect header check
```

**Comment by PiotrMachowski** [comment]
Map Extractor doesn't work in your case, this is a map from Dreame integration - Map Card works with it as well

**Comment by suskozaver** [comment]
Ok, thank you. 
But if I remove the Xiaomi Cloud Map Extractor from HACSs, so my logs stop getting this errors... the Map Card stop working. Is that intentional, or should I ask Dreame developer?

**Comment by suskozaver** [comment]
Nevermind, I retried removing it and the map integration still works.
