### ISSUE TITLE
Map update fails after update to 1.0.8

### ISSUE THREAD

**Issue by FeromonDE** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#95]
```
Logger: homeassistant.helpers.entity
Source: custom_components/xiaomi_cloud_map_extractor/image_handler.py:261
First occurred: 20:41:51 (1 occurrences)
Last logged: 20:41:51
```
```
Update for camera.roborock_s5_max fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 277, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 473, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 200, in update
    map_data = self._connector.get_map(self._country, map_name, self._colors, self._drawables, self._texts,
  File "/config/custom_components/xiaomi_cloud_map_extractor/xiaomi_cloud_connector.py", line 134, in get_map
    map_data = MapDataParser.parse(unzipped, colors, drawables, texts, sizes, image_config)
  File "/config/custom_components/xiaomi_cloud_map_extractor/map_data_parser.py", line 77, in parse
    MapDataParser.draw_elements(colors, drawables, sizes, map_data, image_config)
  File "/config/custom_components/xiaomi_cloud_map_extractor/map_data_parser.py", line 226, in draw_elements
    ImageHandler.draw_path(map_data.image, map_data.path, colors, scale)
  File "/config/custom_components/xiaomi_cloud_map_extractor/image_handler.py", line 133, in draw_path
    ImageHandler.__draw_path__(image, path, ImageHandler.__get_color__(COLOR_PATH, colors), scale)
  File "/config/custom_components/xiaomi_cloud_map_extractor/image_handler.py", line 228, in __draw_path__
    ImageHandler.__draw_on_new_layer__(image, draw_func, scale)
  File "/config/custom_components/xiaomi_cloud_map_extractor/image_handler.py", line 261, in __draw_on_new_layer__
    layer = Image.new("RGBA", size, (255, 255, 255, 0))
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 2634, in new
    return im._new(core.fill(mode, size, color))
MemoryError
```

With 1.0.7 everything work.

**Comment by PiotrMachowski** [comment]
Can you share your config?

**Comment by FeromonDE** [comment]
> Can you share your config?

```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret roborock
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    country: "de"
    name: "Roborock S5 Max"
    draw: ['all']
    colors:
      color_path: [20, 20, 20]
      color_goto_path: [20, 20, 20]
      color_predicted_path: [20, 20, 20]
      color_zones: [255, 255, 255, 60]
      color_zones_outline: [0xAD, 0xD8, 0xFF]
    room_colors:
      16: [240, 178, 122]
      17: [133, 193, 233]
      18: [217, 136, 128]
      19: [52, 152, 219]
      20: [205, 97, 85]
      21: [243, 156, 18]
      22: [88, 214, 141]      
    sizes:
      charger_radius: 22
      vacuum_radius: 27
    map_transformation:
      scale: 10
      trim:
        top: 22
        bottom: 22
        left: 20
        right: 20
    attributes:
      - calibration_points
      - charger
      - image
      - no_go_areas
      - no_mopping_areas
      - room_numbers
      - rooms
      - vacuum_position
      - vacuum_room
      - walls
      - zones
    scan_interval:
      seconds: 10
    auto_update: false
```

**Comment by PiotrMachowski** [comment]
Do you really need scale 10? 😮

**Comment by cristianlazarop** [comment]
That scale thing is the issue... I had a quite big scale setup and I was getting the exact same issue.
After lower a bit the value, everything started working as usual :)
Thanks @PiotrMachowski !!

**Comment by PiotrMachowski** [comment]
@cristianlazarop Bigger scale -> bigger image -> bigger memory consumption -> higher probability of memory shortage

**Comment by FeromonDE** [comment]
@PiotrMachowski Why then did everything work without problems before version 1.0.8?

**Comment by PiotrMachowski** [comment]
Image processing has been changed a little bit to draw paths in a nicer (smoother) way. I will check if it can be improved

**Comment by perseus177** [comment]
Same problem 
**Version HA -  core-2021.5.5
Xiaomi Cloud Map Extractor - v1.1.1**







This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/xiaomi_cloud_map_extractor/xiaomi_cloud_connector.py:124
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 31. mája 2021, 14:00:11 (3 occurrences)
Last logged: 31. mája 2021, 14:00:20

```
Update for camera.xiaomi_cloud_map_extractor fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 316, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 524, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 225, in update
    map_data, map_stored = self._connector.get_map(self._country, map_name, self._colors, self._drawables,
  File "/config/custom_components/xiaomi_cloud_map_extractor/xiaomi_cloud_connector.py", line 129, in get_map
    response = self.get_raw_map_data(country, map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/xiaomi_cloud_connector.py", line 146, in get_raw_map_data
    map_url = self.get_map_url(country, map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/xiaomi_cloud_connector.py", line 124, in get_map_url
    if api_response is None or "result" not in api_response or "url" not in api_response["result"]:
TypeError: argument of type 'NoneType' is not iterable

```

**Comment by PiotrMachowski** [comment]
@perseus177 no, it definitely is not the same problem. Your issue is here: #78

**Comment by Didel** [comment]
I think I am experiencing a similar problem. I got the following errors:

```
Update for camera.xiaomi_cloud_map_extractor fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 401, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 609, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 257, in update
    self._handle_map_data(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 314, in _handle_map_data
    map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 28, in get_map
    map_data = self.decode_map(response, colors, drawables, texts, sizes, image_config)
  File "/config/custom_components/xiaomi_cloud_map_extractor/viomi/vacuum.py", line 15, in decode_map
    return MapDataParserViomi.parse(unzipped, colors, drawables, texts, sizes, image_config)
  File "/config/custom_components/xiaomi_cloud_map_extractor/viomi/map_data_parser.py", line 157, in parse
    MapDataParserViomi.parse_section(buf, 'unknown2', map_id)
  File "/config/custom_components/xiaomi_cloud_map_extractor/viomi/map_data_parser.py", line 313, in parse_section
    raise ValueError(
ValueError: error parsing section unknown2 at offset 0xb882a: magic check failed 0x12a1200
```

My config is relatively simple:

```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_ip
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_username
    password: !secret xiaomi_password
    map_transformation:
      scale: 1
      trim:
        top: 40
        bottom: 45
        left: 45
        right: 31
```

I am using a Xiaomi Mi Vacuum Mop P (Viomi v8). Yesterday after I first set everything up, it worked fine and I was able to see the map being rendered as expected (I also was able to figure out the appropriate trim values). Right now, the vacuum is busy cleaning, and it looks like whatever I try, it can't seem to generate a new map image.
